### ISSUE TITLE
Design icons

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#100]
Need to design the follow icons in a flat, thin style (black on transparent background)

Also must be a png and at least 500px by 500px
- Double exclamation mark
- Trophy
- Lifting weight
- Meditation
- Food
- Hands shaking
- Friends (gender neutral)
- Family (gender neutral
- Partner/spouse/etc. (gender neutral)
- Bandaid
- Star

And whatever else you can think of! :)

**Comment by julianguyen** [comment]
Would this be something you'd be possibly interested in @hellocam? :)

**Comment by hellocam** [comment]
Yes, but I'd probably get to it much later on.  I'll get back to you about it when I'm done with the UX stuff?

**Comment by anne27** [comment]
Working on these!

**Comment by hellocam** [comment]
@anne27 Thank you! I've been swamped and haven't been able to touch any of these! <3
