### ISSUE TITLE
Change form layout in Medications

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#112]
Currently it looks crowded. Any layout change that looks consistent with the other forms in the app is fine :)

![screen shot 2016-05-02 at 4 41 35 pm](https://cloud.githubusercontent.com/assets/3010728/14971209/069dd446-1085-11e6-9ab1-de1a77346b36.png)

**Comment by julianguyen** [comment]
Wanna start working on @aayushpi? :)

**Comment by aayushpi** [comment]
Is there a preferred order that you’ve found helpful, or users have suggested?

**Comment by julianguyen** [comment]
Nope! But I think an order that makes sense when you're reading off your prescription bottle makes most sense.

**Comment by aayushpi** [comment]
![image](https://cloud.githubusercontent.com/assets/2206776/15720879/3976c1ac-27eb-11e6-90ba-97af5c3eacf3.png)
Pass 1.

Still working on this

**Comment by julianguyen** [comment]
Looks great @aayushpi! Hmm but should be using more of the screen width? It looks a little isolated floating in the center? Hmm would it be weird if were left aligned instead?

**Comment by aayushpi** [comment]
It’s not done yet.

1. Screen width: IMO no, there’s a lot of research about fields that are longer than they typically need to be being left incomplete. Our data set is small, so the fields should be as such.

2. Floating in the center looks odd now, but the style isn’t done. Eventually, I still want this centralized but should solve the isolation that comes off.

Also, this may be mobile optimized at this point: needs testing.

**Comment by aayushpi** [comment]
LOTS of styling changes incoming, this page is going to be pretty... ish

**Comment by julianguyen** [comment]
Ah thanks for clarifying! Very interesting that longer fields are often left incomplete >.<

Looking forward to seeing them! Thanks Aayush :)

**Comment by julianguyen** [comment]
@tiffanysun This was something Aayush was working on but didn't get a chance to finish. Would you want to pick up this first? :)

**Comment by tiffanysun** [comment]
@julianguyen sounds good! i'll start here

**Comment by kindlingscript** [comment]
Here's what I've done in Sketch so far, followed with how it looks in my local environment:

![if_me](https://cloud.githubusercontent.com/assets/13127241/19299459/0b6b07d6-901a-11e6-9f8e-a2eefc148aab.png)
To get the header content in Sketch, I screenshot it and placed it in the artboard. I would move the "New Medication" header here to the center if it wasn't an image. Compared to the coded result below (screenshot in Chrome), where I changed as little as possible to start getting the desired result, there's more whitespace in the above Sketch design than I'd like. Personally, I prefer the size of the coded shot below. &cudarrr;

<img width="1435" alt="screen shot 2016-10-12 at 1 17 41 am" src="https://cloud.githubusercontent.com/assets/13127241/19299463/11dd4e1c-901a-11e6-9b60-710495b9acf1.png">
This is just a WIP and isn't a "scrolling screenshot." There's whitespace, but an appropriate amount to let the design breathe (I may add a little bit more, namely between the "Name" part and the section right below). Also, still thinking of putting "New Medication" in the center so the eye doesn't have to move from left-hand side of page to the center.

I'll get back to working on this later today. Let me know your thoughts! 🙂

**Comment by julianguyen** [comment]
This looks awesome @kindlingscript! A lot less cluttered and I like how everything is laid out. Do you want to keep the style of the input fields? 

Also don't forget mobile web :P
 
@hellocam thoughts?
