### ISSUE TITLE
More unit test coverage

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#13]
Ideally, there should be unit tests for every model and controller in the app.

**Comment by tuyen93** [comment]
Hi Julia,

As I plan take only my window laptop with me to San Francisco and leave my old mac pro in Sydney.

Therefore I'll go back to window to set up your 'if-me' project on my local window environment laptop, before I look at your assigned #13 to me in my free time only from my prioritizing of my already busy scheduled tasks in revising my java skills for my USA  employment in San Francisco which I don't know yet how long the contract would be but immigration employment visa is valid for 2 years and could be extended indefinitely for every 2 years, if still employed and sponsored by USA employer (still waiting for written offer letter for San Francisco employment) and packing up my personal belonging for that USA employment trip as well.

Hopefully there might be common parts of front end tasks between Java and Ruby on Rail in term of HTML5, CSS3 and Jquery AJAX library parts I could work on for your 'if-me' project beside rspec rails unit/functional testing.

I'll let you know how I go with setting up my  local window environment laptop.

Tuyen,

Date: Thu, 19 Feb 2015 21:13:03 -0800

**Comment by julianguyen** [comment]
You can definitely do front-end work as well. Just assign yourself to other issues. I assigned you this because you seem to have a lot of experience with testing. You can un-assign yourself from this task if you want :)

Good luck
