### ISSUE TITLE
Add email reminders for upcoming meetings

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#131]
Send Meeting members email reminders for upcoming meetings within 24 hours of the event.

**Comment by tcdowney** [comment]
Hi @julianguyen, is anyone working on this issue?

**Comment by julianguyen** [comment]
Nope! Feel free to work on this! Also email us at join.ifme@gmail.com to be
added to our Slack! Don't forget to add yourself to the Contributors page
too when you're ready.

**Comment by tcdowney** [comment]
Great!  Thanks for getting back with me so quickly.. now time to get this dev environment set up! :full_moon_with_face:
