### ISSUE TITLE
Be able to delete comments

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#132]
Currently, no users are able to delete comments.

We should give the user who created the Moment or Strategy the ability to delete comments.
We should also give any user who posted comments, the ability to delete those comments.

If a comment is deleted, remove all notifications pertaining to that comment.

**Comment by calebthompson** [comment]
I'll take a whack at this.

**Comment by julianguyen** [comment]
@calebthompson Hey thanks but I actually started working on this last night! But I would love help reviewing the code :) Do you want to pick up another issue?

**Comment by julianguyen** [comment]
@calebthompson do you want to take a look at this? https://github.com/julianguyen/ifme/issues/130 😃

**Comment by calebthompson** [comment]
Sure. As I'm digging into things I'm seeing a few places I might be helpful refactoring if that's alright. Hopefully I can move things a little closer to what new devs familiar with Rails are expecting in the codebase, and maybe improve code coverage a bit.

**Comment by julianguyen** [comment]
@calebthompson yes that would be perfect! Thank you :)
