### ISSUE TITLE
Add email reminders for Strategies

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#139]
Strategies are ways in which you can practice self-care. We want to add the option to send email reminders to remind users to perform these strategies.

**Comment by julianguyen** [comment]
@sylviapereira Hey Sylvia! Any updates? :)

**Comment by sylviapereira** [comment]
Hi Julia!
Honestly I'm struggling a bit to get started on this. This is the first big
project I've jumped on and I'm having trouble getting everything up and
running. I bundle installed with no issues, but I can't get it to actually
run on the server, looks like a devise error?

/home/sly/Documents/ifme/ifme/config/initializers/devise.rb:310:in `block
in <top (required)>': undefined method `[]' for false:FalseClass
(NoMethodError)

Is there an api key missing, did I miss a step somewhere?

I'm sorry I've had less time to work on this than I'd thought and it's not
going smoothly, if it'll help move things along I can work on a different
issue once I get things working, I don't want to hold up progress on the
app! :S Also can I be added to the Slack channel, maybe I could ask for
help there on this issue so I'm not bothering you!

- Sylvia

**Comment by julianguyen** [comment]
@sylviapereira Hey Sylvia, sorry to hear that you are encountering setup issues.

Did you do any of the steps in https://github.com/julianguyen/ifme#setting-up-api-keys?

The 3rd party APIs are not necessary if you are do not want to have those features in your local environment, but generating a secret key for the app is necessary i.e.

`Run rake secret to generate a SECRET_KEY_BASE for config/application.yml. This is the only required configuration change.`

Let me know if you're already tried this and what the result was!

**Comment by sylviapereira** [comment]
OK some progress! I had done that but it couldn't find the yml files to
copy... I deleted my fork and started over, tried again and it worked... So
now after generating the secret key and entering it in application.yml,
when I try to run the server I still get:
... yay progress? :)

​

**Comment by julianguyen** [comment]
@sylviapereira Do you still get this error? /home/sly/Documents/ifme/ifme/config/initializers/devise.rb:310:in `block
in <top (required)>': undefined method `[]' for false:FalseClass
(NoMethodError)

**Comment by sylviapereira** [comment]
No, it doesn't look like a devise error any more... a password seems to be
missing somewhere. hmm

**Comment by sylviapereira** [comment]
AH, sorry I sent a screenshot of the errorthat didn't post here, here's what I get 
![screenshot from 2016-05-26 17-51-28](https://cloud.githubusercontent.com/assets/16631225/15591983/47584a60-236e-11e6-88dd-9639e83408e6.png)

**Comment by julianguyen** [comment]
Can you DM me on Twitter your email so I can add you to Slack? :) Easier to carry this conversation there!

**Comment by sylviapereira** [comment]
Sure! :)

**Comment by andela-oesho** [comment]
hello @julianguyen  is this issue still pending?

**Comment by julianguyen** [comment]
This is still pending! Feel free to assign yourself to it if you wanna work on it @andela-oesho :P
