### ISSUE TITLE
Unable to set refill date for medications

### ISSUE THREAD

**Issue by stellacotton** [julianguyen/ifme#140]
When I go to create a new medication with a refill date, it raises an error `NameError Exception: uninitialized constant MedicationsController::Google`

It looks like a version bump on the google-api-client from 0.8 to 0.9 causes breaking changes to the existing API interface: https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md  😿

If 0.8 was working ok and there weren't any features needed in 0.9, it might be worth rolling back to 0.8 and dealing with the upgrade at a later time. I'm happy to roll it back if you don't think it's worth trying to upgrade the gem @julianguyen?

**Comment by julianguyen** [comment]
Good find! V 0.8 was working fine and I don't recall any specific features we needed for 0.9. Rolling back is a good plan then.

That exception is raised when the refill date is saved to Google calendar?

**Comment by stellacotton** [comment]
Ah, yeah I just realized the title of the bug is actually misleading because it does save it to the database but it raises an exception when trying to initialize the Google api to save to the calendar.

**Comment by julianguyen** [comment]
Hmm I think we should add a check box that will save the refill date to Calendar.... that way the user knows thisnks happening and this check box only appears for Google authenticated users.
