### ISSUE TITLE
Streamline dev configuration values into one file

### ISSUE THREAD

**Issue by stellacotton** [julianguyen/ifme#142]
Okay, so not quite one file. 😄  

I chose to do two files since Figaro doesn't store hashes and I didn't want to make the smtp settings in the development.rb by default (because then you'd have to ignore that whole file instead of just your settings file).

#141 uses Figaro and allows for quicker development setup since all api keys and secrets can be updated in two places (and ignored from two places). The config/application.yml and the config/smtp.yml files are the only files that house secrets and are set in the .gitignore by default to prevent accidentally checking in sensitive information.

I do think it could impact production, so we would need to make sure the configuration values are ported over to Heroku environment variables before the code gets merged to master and rolled out.

#141  will impact anyone who currently has their api secrets in the old locations. Files where I extracted the hard coded values include:

```
app/assets/javascripts/notifications.js
app/mailers/application_mailer.rb
config/environments/development.rb
config/initializers/pusher.rb
config/secrets.yml
config/cloudinary.yml
config/initializers/devise.rb
```

and I removed 
```
config/api.yml
```
altogether since I extracted those two secrets into the application.yml

**Comment by julianguyen** [comment]
💯
