### ISSUE TITLE
Dropdown menus in new moments scrolls page up

### ISSUE THREAD

**Issue by gwengrid** [julianguyen/ifme#143]
How to recreate:

1. Click the '+' button to add a new moment
2. Scroll down
3. Open one of the drop down menus on the left, e.g. strategies, moods

Expected: the menu opens
Observed: the menu opens and the page scrolls to the top

**Comment by julianguyen** [comment]
@gwengrid Thanks so much for filing this! Did you this bug occur on a mobile browser or desktop browser?

**Comment by gwengrid** [comment]
@julianguyen Desktop browser! Chrome, if that helps.

**Comment by julianguyen** [comment]
Aha I see what you're talking about! Thanks :)
