### ISSUE TITLE
Creating support groups to share resources and organize meetups

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#15]
* Creating support groups with existing allies
* Having admins manage members and moderate posts
* Posting resources and reviewing them
* Creating meetup/support group events online/offline

**Comment by julianguyen** [comment]
@gCrew Would you be interested in working with me on this? You could work on the design aspect of this feature!

**Comment by gCrew** [comment]
@julianguyen I can definitely work on the design aspect of this. Just tell me the details of what I am expected to know and design because I do not have as much experience. So, I need to get started as soon as possible.

**Comment by julianguyen** [comment]
The work is being done in the support-groups branch! https://github.com/julianguyen/ifme/tree/support-groups. Will send you screenshots on Slack!

**Comment by julianguyen** [comment]
@gCrew I suggest working on adding a calendar and time picker to the feature! Also add any UI enhancement you think is necessary!
