### ISSUE TITLE
Clean up Contributors page

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#155]
The blurbs on the Contributors page are wonderful and important, but as our project expands and more blurbs are added onto the page... we don't want it to become cluttered. 

This is a sample blurb on the page, as you can see it's a little lengthy.
![screen shot 2016-05-25 at 10 31 24 am](https://cloud.githubusercontent.com/assets/3010728/15550000/3f5226e8-2264-11e6-9537-eb6a046190fb.png)

We want to do something like this, where we blur out text after a certain amount of characters (250 characters is a good amount) and when the user clicks on that area the rest of the text expands. No button is necessary!

![screenshot_2016-05-25-10-27-11](https://cloud.githubusercontent.com/assets/3010728/15550002/440a64b6-2264-11e6-9598-1dfef64d02aa.png)

We only want this done with the blurb text, not the name section or the section that has the location/contact info. Also keep in mind that the app is responsive, so your changes must work in mobile web!

We're open any other additional improvements to the design of the page! ^_^
Please add yourself to the page! <3

**Comment by julianguyen** [comment]
@nagmak Would you be interested in working on this? :)

**Comment by nagmak** [comment]
@julianguyen It does sound interesting, I'd like to give it a try!

**Comment by julianguyen** [comment]
@nagmak Awesome! Please accept the collaborators invite so I can assign you to it :P
