### ISSUE TITLE
App Recommendations?

### ISSUE THREAD

**Issue by markfarrell** [julianguyen/ifme#157]
Moments seem to let me talk about either how (I feel like) I'm going nowhere, moving one step forward, or even one step backwards from achieving my mental health goals. However, I still feel like it's largely up to me to figure out how to move two steps forward, and so on, in order to better and better approximate my mental health goals. I find having the right intuition and good sense of judgement can be especially hard when it comes to mental health; sometimes it feels easy to fall into a box, fog, bubble, or whatever you want to call it, and not have the self-awareness or strength to figure out what longer-term sequence of actions to take in the first place. Would it be possible for the app to make recommendations on how to compose tactics (strategies applied to kinds of moments), in order to increase chances of making positive progress long term? How might app recommendations of this sort be possible? Perhaps some combination of allies, support groups, and maybe even "machine learning"? What are you thoughts on having support for recommendations in general?

**Comment by julianguyen** [comment]
That is a very interesting idea. Thanks for bringing it up. We could use common categories tagged in existing strategies and moments to suggest which strategies a user should look at when writing a new moment.
