### ISSUE TITLE
Improve flow of adding categories and moods to triggers

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#16]
Creating categories, moods, and triggers feels like a redundant process. We should combine creating categories and moods while writing triggers (also giving the option for users to add descriptions and manage all categories and moods in one place)

**Comment by balupton** [comment]
has this been closed because it has been done?

**Comment by julianguyen** [comment]
@balupton I closed it because nothing has been changed recently. Are you working on this issue? If so, I can re-open :P

**Comment by balupton** [comment]
no no, just tracking this repo - seems nifty!

**Comment by julianguyen** [comment]
@balupton Hey! Do you want to test out the app help track bugs and feature enhancements? :) If so, feel free to file issues here or fill out http://goo.gl/forms/8EqoJDDiXY
