### ISSUE TITLE
Adding Strategy doesn't show confirmation

### ISSUE THREAD

**Issue by finitem** [julianguyen/ifme#175]
Browser: Firefox 46.0.1
OS: Windows 10
Date: 2016-05-28

Issue: When the user clicks on "create strategy" they remain on the page with the modified strategy, and there is no visible change despite the strategy being added.

![strategy_broken](https://cloud.githubusercontent.com/assets/8795569/15628343/c35571e2-24cc-11e6-97eb-00d010d3b7d5.PNG)

Repro steps:
1. Sign in
2. Go to the "Strategies" tab.
3. Press the "+" symbol to add a new strategy.
4. ! Nothing seems to happen.

Dev notes:
There is a 500 Internal Server Error that gets thrown
![strategy_500](https://cloud.githubusercontent.com/assets/8795569/15628374/4ff48174-24cd-11e6-95c8-4d9a34aff9ee.PNG)

Post parameters:
authenticity_token	[token was here, but seems like a thing that should be secret]
strategy[comment]	0
strategy[description]	testing #2
strategy[name]	    test 2
strategy[userid]	45
utf8	✓

**Comment by julianguyen** [comment]
@finitem Just committed a possible fix, can you retest and let me know what happens? :)

**Comment by finitem** [comment]
retesting now!

**Comment by finitem** [comment]
Success! I was able to get to the confirmed strategy creation/strategy view page. I tested it with the same name and description, and an alternate one, and both worked fine. Seems fixed to me!

**Comment by julianguyen** [comment]
Yasss! Thanks for your help 💯
