### ISSUE TITLE
Moments subheader never dismisses

### ISSUE THREAD

**Issue by finitem** [julianguyen/ifme#176]
Browser: Firefox 46.0.1
OS: Windows 10
Date: 2016-05-28

![mood_subheader_always](https://cloud.githubusercontent.com/assets/8795569/15628441/1f99c7a8-24cf-11e6-95de-beb6d03fd251.PNG)

Issue: When the user mouses over the moments header, the subheader with categories and moods never dismisses, even when selecting something else

Repro steps:
1. Mouse over the moments header
2. Subheader appears
3. Mouse over allies (or anything else)
4. !it's still there

**Comment by julianguyen** [comment]
@finitem to close the moments sub header you need to click on the sub header. Do you think mouse over outside of the sub header should close it though?

**Comment by finitem** [comment]
Hmm, I didn't even think of clicking on it to close it, so that's something to consider. And I think that when it appears via mouse-over, a similar action to dismiss it makes sense from a consistency standpoint. I do know that I would rather it stays forever than I get into the scenario where I'm trying to click on Categories, and when my mouse exits the bounding box of Moments for a brief moment it goes away. So I guess my ideal scenario is that if the mouse is outside of the header and subhead for more than 500ms or something, then it would dismiss? That seems like enough time to signal my intent of not going to that section, but also allows me to take time to move the mouse through outer zones to get to the subheader if I'm going there. I don't know what effect this would have on keyboard/tab navigation, though. Also I'm just one person, so maybe everyone else likes the current way!

If I didn't explain my thoughts clearly happy to rephrase.

**Comment by julianguyen** [comment]
Thanks for explaining! Hmm maybe having an "X" icon would help? Thoughts?

**Comment by julianguyen** [comment]
Changed behaviour so when you mouseover the header navigation, the sub-navigation closes https://github.com/julianguyen/ifme/commit/4794af96728904cd8e3cde9a1b49b7cc183d0e4c

**Comment by julianguyen** [comment]
@finitem updated thoughts? :P

**Comment by finitem** [comment]
@julianguyen I like it! : )
