### ISSUE TITLE
(Unable to repro) Group creation doesn't work

### ISSUE THREAD

**Issue by finitem** [julianguyen/ifme#177]
Browser: Firefox 46.0.1
OS: Windows 10
Date: 2016-05-28

Issue: After entering description and title for group and selecting "Create Group" the page redirects but no group is created.

Notes: Happened the first time, but not on revisiting it. Unless it happens to someone else, may have been user error.

**Comment by julianguyen** [comment]
@finitem Is your email address valid?

**Comment by finitem** [comment]
I used Google Sign in, so presumably it is valid.

**Comment by julianguyen** [comment]
Oh dangg. Hmm and you can't repro it again right? :/

**Comment by finitem** [comment]
Right, unable to repro. If you think it's possibly an email issue, I can make another acct and try to make a group right after account creation and see if that is related. I'll try that now.

**Comment by julianguyen** [comment]
I don't think it's an email issue :/ But maybe try deleting your account and recreating it with the same email and see what happens?

**Comment by finitem** [comment]
I just tried with an alternate email - it worked fine there. I'll try with the original email now too.

**Comment by finitem** [comment]
Works just fine! It's entirely possible that I did something silly like press backspace right when I clicked the button the first time or something. Unless this pops up for someone else I think it might not be an issue.

**Comment by julianguyen** [comment]
Alright I'll close it for now then! Thanks for letting me know :)
