### ISSUE TITLE
Unit tests for JS

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#180]
There are currently no JS unit tests, which is problematic. I've set up Jasmine (https://github.com/julianguyen/ifme#unit-tests), so anyone is welcome to help write tests! :)

A sample test can be found here: https://github.com/julianguyen/ifme/commit/b6f4fb081cc2365142f0150564964698977b17be

**Comment by julianguyen** [comment]
We would like to have individual test specs for
* add_comment.js
* application.js
* charactercount.js
* delete_comment.js
* form_processing.js
* header.js
* medications.js
* meetings.js
* notifications.js
* search.js
* strategies.js

If you need to refactor any of this code, go right ahead :)

**Comment by julianguyen** [comment]
Hey @piecedigital, here's the issue for JS unit tests. Please sync up with @maestromusica to figure out which specs you want to work on :)

**Comment by stellacotton** [comment]
For any new WriteSpeakCode folks, looks like @piecedigital and @maestromusica have done some awesome work on so far:
- header.js
- moments.js
- strategies.js

and the rest could use some love.

**Comment by nchambe2** [comment]
Hey @julianguyen I would be interested in continuing work on this issue.

**Comment by piecedigital** [comment]
@nchambe2 Feel free to work on this issue. As @stellacotton noted the new list should look like this:

* add_comment.js
* application.js
* charactercount.js
* delete_comment.js
* form_processing.js
* medications.js
* notifications.js
* search.js

**Comment by nchambe2** [comment]
Hey @piecedigital, 
I plan to work on this issue today, along with another user @revolaution.

**Comment by julianguyen** [comment]
Hey @nchambe2 @revolaution, could you send join.ifme@gmail.com your emails so I can add you to our Slack channel? Thanks :)

**Comment by piecedigital** [comment]
@nchambe2 Alright. If you have any questions just ask me on Slack. Same name :smiley:
