### ISSUE TITLE
Inserting analytics in the app

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#182]
@kaybarnes raised a really good point about having analytics in the app to figure out how users are using the app! 

I've used Google Analytics in past, but I'm not all too familiar with dealing with data and analytics, does anyone have any other recommendations? :)

**Comment by DeonHua** [comment]
GA is definitely a good (free) solution for analytics - [Mixpanel](https://mixpanel.com/pricing/) is another, but charges for all of its features.

**Comment by julianguyen** [comment]
@DeonHua Ah! Good to know :) Thanks Deon!
