### ISSUE TITLE
Alphabetical ordering of members list in Groups and Meetings

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#186]
Hey @kkelleey! Since you've been working a lot with the Groups and Meetings code lately, I was wondering if you could do this. Thanks :)

![screen shot 2016-05-29 at 6 52 57 pm](https://cloud.githubusercontent.com/assets/3010728/15637879/a250e78a-25ce-11e6-80d9-d07cdcbe3406.png)

Test1 Lastname should appear before Test2 Lastname

**Comment by kkelleey** [comment]
👍  yep!

**Comment by julianguyen** [comment]
Thank you <3 ^_^
