### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#19]
Make the layout responsive for mobile

**Comment by DeonHua** [comment]
Are we using any responsive frameworks right now?

**Comment by julianguyen** [comment]
Nope. I usually make things responsive manually haha. If you know of any good frameworks worth trying, then let me know!

**Comment by DeonHua** [comment]
I usually use Bootstrap, but I think in this case it would be better to work with SASS and [Bourbon Neat](http://neat.bourbon.io/)

**Comment by julianguyen** [comment]
I've written all of the CSS thus far, so a framework like Bootstrap shouldn't be necessary. But Bourbon Neat looks intriguing! Thanks for bringing it up ^_^

**Comment by juliepagano** [comment]
Has there been any movement on this since March? I'm working on a bunch of styling cleanup, so I'm inclined to look at this when I finish that unless someone else objects.

**Comment by julianguyen** [comment]
Nope no movement!

**Comment by jeanieshark** [comment]
@juliepagano I just randomly stopped by here through the Internet rabbithole and would love to help out with this effort. I used to be one of the maintainers of Foundation and would love to help out. :smile:

**Comment by julianguyen** [comment]
@jeanieshark We would love for you to help out! Can you email join.ifme@gmail.com your email address so we can add you to our Slack page? :)

**Comment by emitche** [comment]
I was considering adding Foundation, as it is often what I use. May add it. That way others can easily make items responsive.

I made some responsive changes to the header and that's in a pull request.

Individual pages still need work:
- Triggers
- Strategies
- Medications
- Groups (tweaks)
- Allies (tweaks)

**Comment by julianguyen** [comment]
Sounds good! ++ on Foundation! @jeanieshark would you be interested in helping out with some of the individual pages @emitche listened?

**Comment by jeanieshark** [comment]
@julianguyen @emitche Yes, would love to! I'm finishing up a couple of other personal project at the moment, but would love to help out in a couple weeks!
