### ISSUE TITLE
Cannot uncheck all Categories/Moods/Strategies

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#195]
Steps to reproduce
* Create a Moment
* Select 2 Categories to tag 
* Create
* Edit this Moment
* Uncheck one Category
* Save (works correctly)
* Edit this Moment again
* Uncheck last Category
* Save (does not work correctly and this Category still appears)

**Comment by starbelly** [comment]
@julianguyen bugs  come before features, so I'll knock this out before doing any feature work.

**Comment by julianguyen** [comment]
I think doing this solves the problem

```def moment_params
      params[:moment][:category] ||= []
      params[:moment][:mood] ||= []
      params[:moment][:viewers] ||= []
      params[:moment][:strategies] ||= []

      params.require(:moment).permit(:name, :why, :fix, :userid, :comment, :category => [], :mood => [], :viewers => [], :strategies => [])
    end
```

**Comment by julianguyen** [comment]
Also this issue also exists in strategies_controller.rb

**Comment by julianguyen** [comment]
On a random note @starbelly, I replied to your email and sent you a Slack invite the other day but I got a `Delivery to the following recipient has been delayed` error (I think it's resending). Let me know if you received either!

**Comment by starbelly** [comment]
@julianguyen Had DNS problems the other day, mail is coming through now. Please resend the slack invite.

**Comment by starbelly** [comment]
I did a PR for this. https://github.com/julianguyen/ifme/pull/196 but before we merge, I want to look at this further. Even if you uncheck all categories, etc. category should still be coming back as param, but I haven't looked at all the code yet. My guess without looking is that the form is not structured right.

 Let me look at this, most likely rebase, and then we'll go from there.

**Comment by starbelly** [comment]
@julianguyen Scratch that. Not going to rebase right now. We'll come back to this issue during refactor. Feel free to sign off on this.

**Comment by julianguyen** [comment]
Sounds good! Great work @starbelly 💯
