### ISSUE TITLE
Inviting an ally returns HTTP ERROR 500

### ISSUE THREAD

**Issue by nagmak** [julianguyen/ifme#197]
I've joined the app and tried inviting an ally, but it isn't working.

![screen shot 2016-06-02 at 1 14 42 pm](https://cloud.githubusercontent.com/assets/16668970/15754018/44eaef7a-28c4-11e6-936e-3b1bbf3cc06d.png)
![screen shot 2016-06-02 at 1 15 13 pm](https://cloud.githubusercontent.com/assets/16668970/15754020/48abd610-28c4-11e6-9451-27e1a429b558.png)

**Comment by julianguyen** [comment]
Is this happening locally or in the live app?

**Comment by nagmak** [comment]
It's happening on the live app :S I tried inviting my sister

**Comment by julianguyen** [comment]
Ahh thanks for letting me know! Will look into it soon! Damn thought I fixed this issue XD

**Comment by julianguyen** [comment]
```
Jun 02 10:19:46 ifme app/web.1:    Rendered users/mailer/invitation_instructions.html.erb (8.5ms) 
Jun 02 10:19:46 ifme app/web.1:  Completed 500 Internal Server Error in 33ms (ActiveRecord: 10.1ms) 
Jun 02 10:19:46 ifme app/web.1:  ActionView::Template::Error (translation missing: en.time.formats.devise.mailer.invitation_instructions.accept_until_format): 
Jun 02 10:19:46 ifme app/web.1:       9: <% if @resource.invitation_due_at %> 
Jun 02 10:19:46 ifme app/web.1:      10: <br> 
Jun 02 10:19:46 ifme app/web.1:      11: <br> 
Jun 02 10:19:46 ifme app/web.1:      12: <%= t("devise.mailer.invitation_instructions.accept_until", due_date: l(@resource.invitation_due_at, format: :'devise.mailer.invitation_instructions.accept_until_format')) %> 
Jun 02 10:19:46 ifme app/web.1:      13: <% end %> 
Jun 02 10:19:46 ifme app/web.1:      14:  
Jun 02 10:19:46 ifme app/web.1:      15: <br> 
Jun 02 10:19:46 ifme app/web.1:    app/views/users/mailer/invitation_instructions.html.erb:12:in `_app_views_users_mailer_invitation_instructions_html_erb___1693503552507818467_69917895536280' 
Jun 02 10:19:46 ifme app/web.1:    app/controllers/users/invitations_controller.rb:5:in `create' 
Jun 02 10:19:46 ifme app/web.1:    app/controllers/application_controller.rb:29:in `block in with_timezone' 
Jun 02 10:19:46 ifme app/web.1:    app/controllers/application_controller.rb:29:in `with_timezone' 
``

**Comment by julianguyen** [comment]
This fixes the issue https://github.com/julianguyen/ifme/commit/3832e11d992cb6459c04474e6c37a4fc2c1b3200 but there is another bug with the date being displayed in the email.

![screen shot 2016-06-02 at 1 40 14 pm](https://cloud.githubusercontent.com/assets/3010728/15762261/a1adc3ec-28d1-11e6-9a13-db95f0bbb83a.png)

**Comment by julianguyen** [comment]
The above issue has been fixed with https://github.com/julianguyen/ifme/commit/af6ae5e56f6d354fb03e9abc8a0deb602b5e82d5

Hey @nagmak can you try testing again? :)

**Comment by nagmak** [comment]
Awesome, it's working! :)

![screen shot 2016-06-02 at 7 26 16 pm](https://cloud.githubusercontent.com/assets/16668970/15764322/ee13eee8-28f7-11e6-9d3c-f207a6d0d052.png)

**Comment by julianguyen** [comment]
Yay thanks for filing this bug! LOL I just realized I replaced invitation_due_at with invitation_created_at. Lemme quickly fix that.
