### ISSUE TITLE
Enchancements to news feed

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#2]
* Updates in real time   
* Sorting news by categories
Can be found in app/views/pages/home.html.erb (view) app/controllers/pages_controller.rb (controller, look at home def)

**Comment by tute** [comment]
@julianguyen says in HackerHours Slack:

`app/views/pages/home.html.erb` (when you hit the home button once you have signed in) is a newsfeed.
Right now it just displays posts in ascending order (date/time) from your allies.
I think this newsfeed can be improved to be able to filter by category and mood.

**Comment by loisgh** [comment]
Hi Julia, 

I'm interested in taking on this issue.  I have a comment.  I think it might make more sense to allow them to filter by category and mood rather than just sorting on category.  Although I can probably manage to do both.  Please advise.

**Comment by tute** [comment]
@loisgh, send over your Pull Request and we discuss over specific code! :+1: :)

**Comment by julianguyen** [comment]
Category and mood are good filters!

**Comment by loisgh** [comment]
Hi Julia, 

It seems that a trigger can belong to more than one category.  If a trigger belongs to one or more categories, how do you want the page to look.  eg. trigger-1 belongs to cat-1, cat-2.  So should the page look as follows:

cat-1
  trigger-1 etc ...
cat-2
  trigger-1 etc ...

Also how should the triggers be sorted within the categories?  Should they be sorted by date desc.  That would be my suggestion.

**Comment by tute** [comment]
Your suggestion of ordering newest first within categories would make sense to me.

If a trigger can belong to more than one category, then more than a "category" it seems to be a "tag". Is it worth it to rename the model to denote that potentially confusing behavior?

If we filter by category, would we ever be showing more than one at the same time, or should we allow users to filter by only one?

**Comment by julianguyen** [comment]
:+1: on ordering based on newest first
We should be able to filter by multiple categories
[filter box here]
[list of triggers in ascending order by date/time]

I think "tag" is a good name for this feature actually. It's shorter and it seems that people use "tag" more frequently in their vocabulary than "category". If you want to go through the process of renaming the controller, model, and view accordingly, then go ahead :P

**Comment by julianguyen** [comment]
@tute @loisgh  What do you think of the naming of "trigger"? Do you think it has a negative connotation or is an appropriate term to use?

**Comment by loisgh** [comment]
I'm not sure.  I don't think it has a negative connotation psychologically.  I think it might be a bit confusing technologically.

**Comment by julianguyen** [comment]
What about:
* story
* moment
What are your thoughts on that?
