### ISSUE TITLE
Better error pages

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#20]
Create better 404, 422, and 500 pages that match the UI and are more helpful to the user. Right now, they are pages auto-generated by Rails.

**Comment by jzshen** [comment]
which paths / links trigger these?

**Comment by julianguyen** [comment]
It's triggered by pages that don't exist, pages that are missing model data, etc.
Don't have a definitive list. It's worth investigating more for testing purposes :)

**Comment by georgetoothman** [comment]
interested in contributing to this with @iuliiakot and @NGewirtz from NYC Hacker Hours with thoughtbot. my working branch here: with https://github.com/georgetoothman/ifme/tree/add-error-pages

**Comment by julianguyen** [comment]
Thanks so much @georgetoothman! I'm on the Hacker Hours slack if you want to talk about anything! Feel free to share screenshots here of what you envision these error pages to be like!

**Comment by georgetoothman** [comment]
https://github.com/julianguyen/ifme/pull/60 current status Thanks all for the help

**Comment by julianguyen** [comment]
Awesome work everyone :) +1

**Comment by afeld** [comment]
Sounds like this can be closed?

**Comment by julianguyen** [comment]
Yes!! :dancer:
