### ISSUE TITLE
Move to gemspec

### ISSUE THREAD

**Issue by starbelly** [julianguyen/ifme#200]
Getting into cleaning up the config, I wondered if everyone might want to move the dependencies to a gemspec so that it can be pushed to rubygems.org. If so, I'll do a PR.

**Comment by julianguyen** [comment]
I'm not sure how to do that, but I can figure it out if you need any help!

**Comment by starbelly** [comment]
Oh, I can do it. Just wanted to see if this was worth doing : )

**Comment by julianguyen** [comment]
Awesome! Definitely worth doing!

**Comment by starbelly** [comment]
Actually, doesn't make sense to work on this right now. We'll revisit later.

**Comment by julianguyen** [comment]
Any specific reason why?

**Comment by starbelly** [comment]
Well, at first I was thinking gem it up so that others could easily use it, but that requires turning everything into an engine and/or module, which would be cool, but it's something that needs to happen organically. I jumped the gun : )

**Comment by starbelly** [comment]
Bug fixes in rails. I didn't see any good reason to hang around at 4.2.5. If you feel otherwise, we can bump it back down.
