### ISSUE TITLE
Refactor schema  and migrations

### ISSUE THREAD

**Issue by starbelly** [julianguyen/ifme#204]
Refactoring the schema has been discussed, opening it as an issue. 

@julianguyen  Why are the migrations consolidated into setup_database, etc?

**Comment by julianguyen** [comment]
@starbelly I don't have a specific answer to that, I think that was done out of convenience. Don't we need an initial migration anyways?

**Comment by starbelly** [comment]
@julianguyen That's fine :) My question was why were the migrations lumped into one file? I don't necessarily have a problem with that and see the utility in it, but, I just wanted to know why.

**Comment by julianguyen** [comment]
I haven't created a migration to get rid of this model yet, but could you get rid of Support and any references (they should be all gone by now) or tests related to it?

**Comment by starbelly** [comment]
@julianguyen Yes. FYI, we're going to do several PRs in regards to this issue. I'll be doing the first PR tomorrow.

**Comment by julianguyen** [comment]
Awesome sounds good!

**Comment by starbelly** [comment]
@julianguyen Let's continue this discussion on this PR: https://github.com/julianguyen/ifme/pull/207

**Comment by starbelly** [comment]
Good luck.
