### ISSUE TITLE
Refactor JS show/hide functions to not use `click_flag`

### ISSUE THREAD

**Issue by sienatime** [julianguyen/ifme#231]
We're already very close to being able to do this, but in `header.js` and `notifications.js` we keep track of how many times something has been clicked (`click_flag`) and do a `% 2` on it to see whether we should hide or show it... this isn't necessary, as we already know if something is open or closed based on the CSS classes applied to it, so we just need to do the opposite of that. jQuery also has a `toggleClass` method (http://api.jquery.com/toggleclass/) that can add a class when it doesn't have it, and remove it when it does. This could be a good first PR for somebody.

**Comment by rashmiagar** [comment]
I would like to take up this issue as a first PR.

**Comment by sienatime** [comment]
@rashmiagar Great! Let me know if you have any questions.
