### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#24]
We should have a code of conduct for team communication (particularly on Slack).

**Comment by icechen1** [comment]
I used http://opensourcebridge.org/about/code-of-conduct/ as a template for
a hackathon I organized earlier this month. This might help :)

On Mon, Mar 23, 2015 at 9:48 PM, Julia Nguyen <notifications@github.com>
wrote:

> We should have a code of conduct for team communication (particularly on
> Slack).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianguyen/ifme/issues/24>.
>



-- 
Regards,
Yu Chen Hou
yuchenhou.com

**Comment by janinecodes** [comment]
A lot of people seem to like AlterConf's Code of Conduct: http://www.alterconf.com/code-of-conduct

I'm sure it could be revised for communication (rather than conference attendance) purposes.

**Comment by julianguyen** [comment]
These look like great resources! If anyone wants to help write this, assign yourself the task (I will be working on it too).

**Comment by juliepagano** [comment]
Some folks are using contributor covenant, which is a really nice wording targeted specifically at open source projects.

https://github.com/CoralineAda/contributor_covenant

**Comment by julianguyen** [comment]
Thanks @juliepagano for suggesting Coraline's contributor convenant!
