### ISSUE TITLE
Travis CI needs to run Jasmine tests

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#245]
Thanks @sienatime for noticing that Travis CI wasn't actually running the Jasmine tests. Oof. 

@starbelly originally set up Travis CI here: https://github.com/julianguyen/ifme/pull/198/files

I modified the Rakefile to run both rspec and Jasmine, but it is not working. https://github.com/julianguyen/ifme/commit/b21d3f31a283b4c97be2018d8ef126d1e793d987

Help is appreciated :)

**Comment by julianguyen** [comment]
Fixed by @starbelly! Thank you ^^

**Comment by starbelly** [comment]
@julianguyen No problem : )
