### ISSUE TITLE
Fix suggested bug risks from eslint (JS) in Codeclimate

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#250]
Go through these bug risks (https://codeclimate.com/github/julianguyen/ifme/issues?category=bugrisk&engine=eslint&page=1&severity=) and fix them! :)

**Comment by rashmiagar** [comment]
May I help with this :)

**Comment by julianguyen** [comment]
Yes please @rashmiagar!!!

**Comment by julianguyen** [comment]
Also @rashmiagar, do you mind emailing join.ifme@gmail.com your email so we can add you to Slack :)

**Comment by julianguyen** [comment]
Added JSHint and started to fix some of the errors: https://github.com/julianguyen/ifme/commit/51e652bd4a83cdf8495148ece34f0d79551b938d

**Comment by deejayres** [comment]
How are we doing here? Do you all still need help with some of this?

**Comment by julianguyen** [comment]
@deejayres This issue is still open! You're welcome to work on it as well. Can you email us at join.ifme@gmail.com so we can add you to our Slack? Thanks :)

**Comment by deejayres** [comment]
@rashmiagar where you are at with this? Should I start from the bottom of the list and work up?

**Comment by julianguyen** [comment]
@deejayres Bottom up should be fine!

**Comment by deejayres** [comment]
#277
