### ISSUE TITLE
UI bug: long text in categories/moods/strategies stats

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#268]
When there are three (max) items in the stats bar and one item takes up multiple lines, this happens:
![screen shot 2016-09-11 at 10 02 02 am](https://cloud.githubusercontent.com/assets/3010728/18419020/0c2edb64-7807-11e6-9a78-2878a0679e33.png)

When this happens, I think the item's height should be consistent with the other ones. In that case, we need to either shrink the font when this happens or cut the text e.g. "Long text bla...".

Thoughts?

**Comment by haleyelder** [comment]
Making the font smaller would keep it on one line, as long as it's not TOO small to read. I was going to say maybe decrease the padding, but then the box would be too close to the words and still look odd.

**Comment by julianguyen** [comment]
@haleyelder Ooh great suggestions. Hmm yeah this is a tough one to solve. On mobile web, the items stack on top of each other. Is this an issue you would like to work on? :)

**Comment by sienatime** [comment]
If you want to make it easy, you can add a css rule to make it add an
ellipsis if if is too long (
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow). It will
get cut off but won't mess with the height. Changing font size is actually
pretty hard (unless you know something I don't @haleyelder 😉)

**Comment by mermop** [comment]
Hi! I found this project through Hacktoberfest, it's a great idea and I'd love to contribute :)

This should be fixable (on IE10+) with `display: flex` and `align-items: stretch` - do you have browser support guidelines, ie do you mind if it looks different on Internet Explorer 8 & 9 and Android 2.3 stock browser?

**Comment by tymeart** [comment]
You might be able to fix this by including `white-space: nowrap` and setting min-width on the items.

**Comment by julianguyen** [comment]
Hey @mermop! Feel free to make a PR! :)
@tymeart Good suggestion! But it might be a little tricky figuring out what the min-width should be.

**Comment by julianguyen** [comment]
Also! @mermop and @tymeart, please email join.ifme@gmail.com to be added to our Slack :D
