### ISSUE TITLE
Using grid layout on Categories/Moods/Medications index pages

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#278]
Each item (Category/Mood/Medication) on the index page takes up the full width of the screen, which is unnecessary given amount of content in the div. Let's use flex boxes to create a grid to display these items! On mobile web view, each item should take up the full width.

![screen shot 2016-09-25 at 3 59 53 pm](https://cloud.githubusercontent.com/assets/3010728/18818856/823074ca-8339-11e6-8a58-f5bf95a932b4.png)

**Comment by Wowu** [comment]
I will fix it.
