### ISSUE TITLE
Be able to auto select checkbox of newly created Category/Mood/Strategy in a Moment/Strategy

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#288]
Current behaviour:
1) Create a Mood through new Moments page:
![screen shot 2016-10-01 at 3 41 03 pm](https://cloud.githubusercontent.com/assets/3010728/19017439/ff70003c-87ed-11e6-92b7-25f00d1f9dc8.png)

2) Does not get auto-checked once created.
![screen shot 2016-10-01 at 3 41 13 pm](https://cloud.githubusercontent.com/assets/3010728/19017438/ff6f11b8-87ed-11e6-94ef-e24f0ee1ff58.png)

Expected behaviour:
1) Create a Mood through new Moments page
2) Does get auto-checked once created

We want this to work for the following:
- New Category in Moments
- New Mood in Moments
- New Strategy in Moments
- New Category in Strategies
- New Mood in Strategies

**Comment by yigitozkavci** [comment]
I'm working on this! :)
