### ISSUE TITLE
Triggering Devise related emails does not work

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#289]
Found by @sienatime!

Triggering either the Devise account confirmation instructions, the reset password email, or confirmation instructions don’t seem to work.

When forgetting password:
`Net::SMTPSyntaxError (501 Syntax error`

```
  app/controllers/application_controller.rb:29:in `block in with_timezone'
  app/controllers/application_controller.rb:29:in `with_timezone'
```

**Comment by pcofilada** [comment]
@julianguyen I'll take a look on this.
