### ISSUE TITLE
Handle empty space in grid layout on index pages when there are an odd number of tiles

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#295]
Huge thanks to @Wowu who added grid layouts to the app! 

It would be neat to add a tile in the empty space that shows up when there are odd number of items. This tile could be a button to add a new Moment/Strategy/Category/Mood/Medication. This tile would have a `$secondary-text-color: #6D0839;` background and have the same plus icon used below positioned in the vertical and horizontal center of the tile
![screen shot 2016-10-02 at 12 17 08 pm](https://cloud.githubusercontent.com/assets/3010728/19023064/2cc2cf90-889a-11e6-8685-bae9a4a102fa.png)

![screen shot 2016-10-02 at 12 06 07 pm](https://cloud.githubusercontent.com/assets/3010728/19023021/3c50fbcc-8899-11e6-8444-852cb557317a.png)

On an even number of tiles, we could have a tile that takes up the full width of the container.

Hovering on this tile would have the same hover state as the plus icon in the sub-header.
![screen shot 2016-10-02 at 12 20 38 pm](https://cloud.githubusercontent.com/assets/3010728/19023095/bccd1eba-889a-11e6-9ce7-1a6950623981.png)

EDIT: Feel free to suggest other ways to handle this empty space!

**Comment by Wowu** [comment]
Are you sure this thing is necessary? IMHO such big button won't be looking good and it won't improve overall UX. E.g. it's visible when user has one Moment, but when he adds next this button disappears. It can be litte confusing.

BTW can you add me to if-me slack team? :smiley:

**Comment by julianguyen** [comment]
A possible alternative @Wowu is to have the tile span the full width of the container if there is an odd number on that row. Anyways we should chat more on Slack :P Email us join.ifme@gmail.com :)

**Comment by julianguyen** [comment]
Closing this for now since there's still a lot of debate whether to even deal with the blank space.
