### ISSUE TITLE
Refactor CSS by putting px values into a _values.scss

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#299]
We should organize our px values in the CSS. Create a `_values.scss` file, similar to `_colors.scss`, and replace all of the px values with variables.

**Comment by imgarylai** [comment]
I can help with this issue!

**Comment by julianguyen** [comment]
That would be awesome @imgarylai! Please email us at join.ifme@slack.com so you can be added to our Slack. Also don't forget to add yourself to the Contributors page :)

**Comment by julianguyen** [comment]
Looks like @zachariast and @imgarylai are working on this. Can you two sync on Slack on how to split up the work? Also feel free to make checklists here too.

**Comment by imgarylai** [comment]
Sorry for that, I am a little bit busy recently. I'm not sure when can I resolve this issue. 

I saw @zachariast 's pull request. Please keep working on this! If I have time to work on this issue again, I will sync code with you. Thanks!
