### ISSUE TITLE
"Select all" checkbox behavior

### ISSUE THREAD

**Issue by Wowu** [julianguyen/ifme#301]
I think that behavior of "Select all" checkbox (in `/moments/new` and `/strategies/new`) is kinda weird

![image](https://cloud.githubusercontent.com/assets/6865958/19043401/441ee092-8990-11e6-8805-7e9247be22d6.png)

It should be rather something like this http://codepen.io/veerkun/pen/oAHCG

What do you think about it?

**Comment by julianguyen** [comment]
Ooh I like the JS refactor in your codepen! Go with it. Should the "Select all" text still change to "Unselect all" though?

**Comment by Wowu** [comment]
Changing text IMO isn't a good idea, I've never seen such solution before.
By the way, this codepen is not mine, first result from Google :smile:

**Comment by julianguyen** [comment]
Feel free to work on this then! I'm open to not changing the text.
