### ISSUE TITLE
Only display clear button in notifications modal when there are notifcations

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#303]
The current behaviour when there are no notifications:
![screen shot 2016-10-03 at 10 56 42 pm](https://cloud.githubusercontent.com/assets/3010728/19064088/aeccedc2-89bc-11e6-9067-4ee13c305f01.png)

![screen shot 2016-10-03 at 10 53 48 pm](https://cloud.githubusercontent.com/assets/3010728/19064050/80255158-89bc-11e6-8c38-0466d6101e5b.png)

In this case, we want to hide the Clear button.

**Comment by zachariast** [comment]
Can i work on that?
