### ISSUE TITLE
Unoptimized images (lots of extra data sent)

### ISSUE THREAD

**Issue by Andykmcc** [julianguyen/ifme#306]
The If Me home page is 7.4MB. It is mostly image data. All other pages come in around 5.5MB with the exception of contributors at 18MB (but my guess is that is a low traffic page so transfer size is less important).

This seems very high to me for a Rails app. cache-control is set so users only have to pay this fee once for the most part.

**Comment by julianguyen** [comment]
https://github.com/julianguyen/ifme/pull/307

**Comment by Andykmcc** [comment]
fixed https://github.com/julianguyen/ifme/pull/307
