### ISSUE TITLE
More test coverage for Rspec/complete empty test specs

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#311]
I noticed there are a handful of empty test specs that _should_ be completed.
- [x] meeting_controller_spec.rb (reading @cpanato)
- [x] pages_controller_spec.rb (in progress @brunoocasali)
- [x] notifications_controller_spec.rb (in progress @tcdowney)
- [x] search_controller_spec.rb (in progress @brunoocasali)
- [x] strategies_controller_spec.rb (in progress @talum)
- [x] notification_spec.rb (in progress @talum)

Feel free to assign yourself to to a spec and let us know in this issue that you're working on it.

**Comment by brunoocasali** [comment]
@julianguyen I'will do the `search_controller_spec.rb` Okay?

**Comment by julianguyen** [comment]
@brunoocasali Thanks a lot! I'll assign you to this issue too. Please email join.ifme@gmail.com to be added to our Slack. Also! Add yourself to the contributors page when you're ready!

**Comment by tcdowney** [comment]
Hi all, I'll fill in some tests for the `notifications_controller_spec.rb`. :)

**Comment by talum** [comment]
Hello! I'd love to write some specs for `notification_spec.rb` and I can take a crack at the `strategies_controller_spec.rb`!

**Comment by julianguyen** [comment]
Looks like @tcdowney is working on notifications but you can sync with him if you want to help out. Strategies is good to take on! I'll add you as a collaborator - assign yourself to the issue. Also! Email join.ifme@gmail.com to be added to our Slack. Add yourself to the Contributors page when you're ready too. Thanks :)

**Comment by tcdowney** [comment]
@talum @julianguyen 

I only wrote specs for the `NotificationsController`, not the model spec since it was listed separately in this issue.  Feel free to work on it @talum!

**Comment by julianguyen** [comment]
Unassigned myself from `meeting_controller_spec.rb` - reviewing PRs right now and fixing a few bugs. Anyone feel free to pick it up, just let us know here.

**Comment by cpanato** [comment]
I can try the meeting_controller_spec :)

**Comment by brunoocasali** [comment]
I've added the `pages_controller.rb` I'm already doing here: #326

**Comment by julianguyen** [comment]
Hey @cpanato! Feel free to work on it! :D

**Comment by cpanato** [comment]
I submit this initial PR #345
However where can I ask questions and clarifications ?
