### ISSUE TITLE
Responders Gem

### ISSUE THREAD

**Issue by brunoocasali** [julianguyen/ifme#315]
Hello guys, what do you thing to setup the responders gem to our code?! Looks pretty nice to remove code like these:

``` ruby
respond_to do |format|
  format.html { redirect_to group_path(@meeting.groupid) }
  format.json { head :no_content }
end
```

**Comment by brunoocasali** [comment]
@julianguyen I can do this refactor, but I will need a very complete test into views (like a user, if someone that knows better the system can help it will be good).

**Comment by julianguyen** [comment]
Right now the test coverage for views isn't complete. So perhaps setting up tests there first would be s good start. Why not use a shared helper method instead is relying on a gem?

**Comment by julianguyen** [comment]
What kind of things would this gem add that writing our own methods wouldn't have? :P

**Comment by brunoocasali** [comment]
I can write something about gem to you, but It will be incomplete ahahahah, please see the [readme of the gem](https://github.com/plataformatec/responders) :+1: 

About test coverage I agree with you!

**Comment by julianguyen** [comment]
Ok I'm fine with using this gem. Thanks!
