### ISSUE TITLE
Specs with js set to true fail in the Docker container created with this Dockerfile

### ISSUE THREAD

**Issue by esBeee** [julianguyen/ifme#317]
Running all specs in the Docker container created with the `Dockerfile`, that is part of this repository, results in 2 failing specs. The reason in both cases is

```
Selenium::WebDriver::Error::WebDriverError:
       Could not find Firefox binary (os=linux). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path=
```

Is this by design or should the dependecy be added to the `Dockerfile`?

**Comment by julianguyen** [comment]
@esBeee Selenium should be running properly. Perhaps add it to the dockerfile?

**Comment by julianguyen** [comment]
Also, do you have Firefox installed?

**Comment by esBeee** [comment]
I have Firefox install on my machine, but it's not accessible from inside a Docker container. I wasn't able to find a simple solution for that problem, but since I'm a user of Docker Compose anyways, I implemented a solution using it. I don't know whether this is where you want to go with Docker, but I've created a pull request, so it's up to you to decide. #332
