### ISSUE TITLE
Use HTTP DELETE instead of GET for destructive NotificationsController#clear action

### ISSUE THREAD

**Issue by tcdowney** [julianguyen/ifme#320]
Notifications for a user can currently be cleared by visiting the following route:

```
clear_notifications GET      /notifications/clear(.:format)               notifications#clear
```

Since the action is destroying all of a user's notifications, it should be an HTTP `DELETE` request instead of a `GET` since it is neither safe nor idempotent. ([reference](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html))

Moving away from `GET` also has the added benefit of letting us use Rail's CSRF security token in these requests. 🎃  🌝

**Comment by tcdowney** [comment]
I plan on finishing this up after https://github.com/julianguyen/ifme/pull/319 is merged so that there  are some tests covering this functionality before I change it.

**Comment by julianguyen** [comment]
I 💯  support this refactor 👍
