### ISSUE TITLE
Unable to successfully access site

### ISSUE THREAD

**Issue by kindlingscript** [julianguyen/ifme#323]
Hi everyone 👋 ,

I brought up this issue to Julia when requesting access to the Slack channel, and she suggested filing an issue about it here, so here I am. 🙂

I found out about this app through Newbie Coder Warehouse on Facebook, and then following that link to the If Me Facebook page, I clicked on the link to the website.

On doing so, I was greeted with this page:

<img width="1436" alt="screen shot 2016-10-10 at 7 41 42 pm" src="https://cloud.githubusercontent.com/assets/13127241/19255254/9f6bcca8-8f21-11e6-81fa-94196dd8568c.png">
For this screenshot, I am on Google Chrome Version 53.0.2785.143 (64-bit).

I went into my settings, cleared my cookies:

<img width="698" alt="screen shot 2016-10-10 at 7 43 57 pm" src="https://cloud.githubusercontent.com/assets/13127241/19255281/eeb2200a-8f21-11e6-8d06-5eaa75ba8e8b.png">
<img width="489" alt="screen shot 2016-10-10 at 7 45 02 pm" src="https://cloud.githubusercontent.com/assets/13127241/19255329/55adee60-8f22-11e6-92c4-1d4238bd8422.png">

The issue did not resolve itself after doing this and closing/re-opening Chrome, so I then tried to block/refuse cookies in general, but that did not work either.

I also attempted to access the site with Firefox and Safari, but neither of those would work.

<img width="1437" alt="screen shot 2016-10-10 at 7 48 40 pm" src="https://cloud.githubusercontent.com/assets/13127241/19255358/b517a148-8f22-11e6-8ac9-85cbc8ffeecb.png">
Firefox 47.0

<img width="1438" alt="screen shot 2016-10-10 at 7 51 00 pm" src="https://cloud.githubusercontent.com/assets/13127241/19255383/e84b5640-8f22-11e6-9144-8a74c9926aad.png">
Safari Version 10.0

I also input the URL in myself, instead of using a link, and got the same issue.

It may be something simple I haven't done, but I'm at a bit of loss now as to the solution. This sort of issue has only happened to me at one other time on one other website, but that resolved itself. I am wondering if it has anything to do with being automatically redirected to "http://www.if-me.org/users/sign_in" when being linked to or going to "http://if-me.org"?

**Comment by deejayres** [comment]
Replicated in Safari for iOS 10

**Comment by brunoocasali** [comment]
Sorry guys, that's my fault :/ I merged a correction see: #324
