### ISSUE TITLE
Global variables is a code smell

### ISSUE THREAD

**Issue by brunoocasali** [julianguyen/ifme#328]
Rubocop, Codeclimante don't love global variables, there are a good reason too. What I want to talk here is about the `$per_page` variable declarated on application_controller.rb it could be removed using Kaminari configuration file!

Just generating: `rails g kaminari:config`

**Comment by julianguyen** [comment]
Ooh! Thanks for pointing this out @brunoocasali. I'm down for this refactor if it means cutting down on global variables.
