### ISSUE TITLE
Fix "Similar code" issue in app/controllers/moments_controller.rb

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#331]
Similar code found in 4 other locations (mass = 49)

https://codeclimate.com/github/julianguyen/ifme/app/controllers/moments_controller.rb#issue_57fced2bbf7c610001000890

**Comment by Fahrenhei7** [comment]
Are we supposed to solve only this one with 4 repeatings? Or all the duplications?

**Comment by andela-oesho** [comment]
can i claim this issue please?

**Comment by julianguyen** [comment]
Yes @andela-oesho! That would be rad :) 

Email us at join.ifme@gmail.com to be added to our Slack too. Don't forget to add yourself to the Contributors page when you're ready!

**Comment by andela-oesho** [comment]
@julianguyen the issue has been fixed, I raised a PR for it. https://github.com/julianguyen/ifme/pull/335
