### ISSUE TITLE
Improve UX in Moments/Strategies sidebar

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#333]
![wsc_opensourcehours](https://cloud.githubusercontent.com/assets/3010728/24170861/8127b1ba-0e3f-11e7-8b0b-dcfe8661b3b9.png)

This is the sidebar that appears in Moments/Strategies, with the Moods toggle opened. Here are few suggested enhancements for this sidebar:
- A way to search and filter out Categories/Moods/Strategies (scrolling through a long list of them is not a good experience)
- A more efficient way to search and add viewers
## Mobile web:

![screen shot 2016-10-11 at 8 56 51 pm](https://cloud.githubusercontent.com/assets/3010728/19297104/6f749da6-8ff6-11e6-94ef-72ed013d3f38.png)
## Desktop:

![screen shot 2016-10-11 at 8 51 55 pm](https://cloud.githubusercontent.com/assets/3010728/19296951/f70e89c2-8ff4-11e6-9bae-8cfe168f1be2.png)

**Comment by kangashley** [comment]
Hi Julia, it's [@softandfierce](https://twitter.com/softandfierce)! 👋  Always wanted to contribute to _if me_ and confident in looking into this issue! Any documentation on or ability to reach out to users who can help test improvements would be helpful.

_Hacktoberfest 2016 🎃_

**Comment by julianguyen** [comment]
@kangashley Hey Ashley! That would be awesome! I think you already on our Slack but if not let me know! @kindlingscript also expressed interest on this issue, so you two should work together on it :)

**Comment by kindlingscript** [comment]
Hi Ashley, I'd love to work together on this issue. 😄 I'd talked a bit about it with Julia, playing around with the idea of incorporating autocompletion (would using a gem be best for this? I've only done so with vanilla JS before) so people can start typing in their mood/category/strategy, and if it's already in their db, it'll come up; if not, they can add a new mood/category/strategy. Let me know if you have other ideas! You can ping me on Slack with this same username.

**Comment by julianguyen** [comment]
How is this going @kindlingscript @kangashley?

**Comment by kindlingscript** [comment]
Sent you a message on Slack, @julianguyen! So sorry for just getting back with you now, the past couple of weeks have been 💨

Sidenote, if anyone wants to help with this, I'm open to it 👍

**Comment by julianguyen** [comment]
How's this going @kindlingscript?

**Comment by kindlingscript** [comment]
Hi, Julia! Just saw this now. I'll ping you over on Slack now about it. 📨

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Improve UX in Moments/strategies sidebar](https://trello.com/c/qjtvuUmL/28-3-improve-ux-in-moments-strategies-sidebar)
