### ISSUE TITLE
Setting up automated deployment

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#338]
Branch: https://github.com/julianguyen/ifme/tree/devops/local-env
- [x] Add `dotenv` gem
- [x] Move `.yml` config files to `.env`
- [x] Update README.md.
- [x] Spread to other collaborators about it.
- [x] Setup CircleC.I.
- [x] Add Circle badges to project.
- [x] Add webhooks checks to pull requests.
- [x] Don't allow directly pushes to master.

**Comment by brunoocasali** [comment]
@julianguyen what about this issue?

There are only two items to solve, I have no permission to avoid pushes on master, and you have the influence needed to tell others about it! ;)
