### ISSUE TITLE
Add contact email in code_of_conduct.md

### ISSUE THREAD

**Issue by andrezacm** [julianguyen/ifme#346]
In `Enforcement` session:
`Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. `

**Comment by julianguyen** [comment]
Ooh thanks for finding this!

**Comment by andrezacm** [comment]
what email would be the right address to add here?

**Comment by julianguyen** [comment]
@andrezacm join.ifme@gmail.com :D

**Comment by andela-oesho** [comment]
@julianguyen  is anyone working on this issue?

**Comment by julianguyen** [comment]
No is @andela-oesho, feel free to take it! :)

**Comment by andela-oesho** [comment]
ok thanks I will be taking it up @julianguyen
