### ISSUE TITLE
Use jasmine-jquery in JS tests

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#362]
![wsc_opensourcehours](https://cloud.githubusercontent.com/assets/3010728/24170861/8127b1ba-0e3f-11e7-8b0b-dcfe8661b3b9.png)

Update JS tests to use jasmine-jquery fixtures and matchers
https://github.com/velesin/jasmine-jquery
- [x] HeaderSpec.js (@julianguyen)
- [x] MomentsSpec.js (@liirene1)
- [x] NotificationsSpec.js (@julianguyen)
- [x] StrategiesSpec.js (@liirene1)

Assign yourself to this issue and put your name beside the spec file you are working on.

**Comment by grrrero** [comment]
Hi @julianguyen, do you have time to show me what I need to do for this one? I'd like to assign myself to one, but I'm not sure what to do/how to go about it.

Thanks. :)

**Comment by liirene1** [comment]
Not sure how to assign myself to this issue, but I'm doing the MomentsSpec.js
