### ISSUE TITLE
Stories cards looking cluttered

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#367]
![wsc-opensourcehours](https://cloud.githubusercontent.com/assets/3010728/20331349/a8666b66-ab59-11e6-9186-ba4c64e59178.png)

The area with the Categories, Moods, and Strategies links is looking pretty cluttered.

<img width="668" alt="screen shot 2016-11-12 at 6 54 22 pm" src="https://cloud.githubusercontent.com/assets/3010728/20243370/86fd4c44-a909-11e6-9e37-384b36fe860c.png">

**Comment by lisavogtsf** [comment]
Can we get some more clarity on this issue? From our understanding, we'd add more white space between the categories, moods, and strategies lines. Is this what you intended?

**Comment by lisavogtsf** [comment]
Starting work on this during open source hours 11/15/16
