### ISSUE TITLE
Add dropshadow on modal titlebar upon scrolling

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#375]
Render a dropshadow at the bottom of the titlebar when the user starts to scroll through the modal

Current behaviour:
<img width="290" alt="screen shot 2016-11-18 at 12 19 29 am" src="https://cloud.githubusercontent.com/assets/3010728/20423384/c48ed43c-ad24-11e6-8152-1216cabe78e4.png">

**Comment by arssonist** [comment]
I'll take a shot at this one.

**Comment by lisavogtsf** [comment]
Kicking off some work on this

**Comment by julianguyen** [comment]
How is this going @arssonist?

**Comment by arssonist** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hey,
I'm so focused on non ruby stuff, last ditch effort to get a job b4 I give up on programming for a profession,that I won't be able to get it done. I didn't understand what to do and Google search seemed to turn up dif variations was also a factor. Not enough focus on Css or ruby on my part I guess.
Anyway, sorry about that.  I guess take me off that case. I'll come back if I ever have more ability to commit. I.e I don't have to stress so much over being annually unemploymed
Chris 


Sent from Yahoo Mail for iPad


On Friday, February 24, 2017, 9:54 PM, Julia Nguyen <notifications@github.com> wrote:


How is this going @arssonist?

**Comment by devishi** [comment]
The above menu is nowhere to be seen. Where do we need to add the drop shadow?

**Comment by julianguyen** [comment]
One place you can access the modal for instance is if you like the "Categories and Moods" link

![image](https://cloud.githubusercontent.com/assets/3010728/23591405/d475c8b8-01a4-11e7-8dee-2945f7e9ef28.png)

**Comment by su6a12** [comment]
Hey Julia,

I'm playing around with this and got it so the drop shadow shows up. Is this good or do you only want it to show up when user starts scrolling?
<img width="863" alt="screen shot 2017-04-18 at 5 28 42 pm" src="https://cloud.githubusercontent.com/assets/6955254/25158363/b7425d94-245c-11e7-8fd1-2c9761bd711a.png">
