### ISSUE TITLE
Generate slugs for individual pages for Moments/Strategies/Moods/Categories/Medications/Groups/Meetings

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#376]
Accessing an individual page for a Moment looks like this for example `moments/1` where 1 is the id. We want to replace this with `moments/name-of-moment-slug` so that it's more readable. Also make sure to handle duplicate slugs e.g. `moments/cool-sluggy` and `moments/cool-sluggy-2` etc.

- [x] Moments
- [x] Strategies
- [x] Moods
- [x] Categories
- [x] Medications
- [x] Groups
- [x] Meetings

Perhaps this gem is useful? https://github.com/norman/friendly_id

**Comment by brunoocasali** [comment]
@julianguyen this gem is fantastic! I agree with this change!
