### ISSUE TITLE
Allies heading showing up when there are no allies

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#383]
Allies heading showing up when there are no allies (from the Allies page)

Example:
<img width="1423" alt="screen shot 2016-11-24 at 6 28 27 pm" src="https://cloud.githubusercontent.com/assets/3010728/20612930/de9d5a70-b273-11e6-90ab-acc53a5192c5.png">

Expected behaviour: hide heading

**Comment by andela-oesho** [comment]
![image](https://cloud.githubusercontent.com/assets/14160244/20650877/5cd40724-b4d9-11e6-9f08-2c74b77a6ebd.png)

hi @julianguyen i think this issue has been resolved
