### ISSUE TITLE
Add some info about the letter_opener gem in the README

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#390]
Mention in the readme me that this gem (https://github.com/ryanb/letter_opener) is used in both the test and development environments to send emails. Instead of emails being sent through SMTP, the email template will open in a new tab. Please also mention that you can disable this gem to test actual emails.

**Comment by estermer** [comment]
Submitted a pull request for this update. p.s. this will be my very first contribution to an open source project! woot woot!

**Comment by estermer** [comment]
made the changes
