### ISSUE TITLE
Blocked HTTP request for location autocomplete

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#417]
`Mixed Content: The page at 'https://www.if-me.org/users/edit' was loaded over HTTPS, but requested an insecure script 'http://gd.geobytes.com/AutoCompleteCity?callback=jQuery1111010604214778680787_1484344551108&q=TOront&_=1484344551109'. This request has been blocked; the content must be served over HTTPS.`

Fixing this bug requires updating the url to `https`. Location autocomplete is used in the sign up form and edit account form.

EDIT: Can't use Geobytes with SSL unless you pay for a license. I will be using Google's Maps API for this.

**Comment by mercyg** [comment]
Hi  @julianguyen  I would like to work on this issue. Could you please tell me where to start?

**Comment by julianguyen** [comment]
I actually picked this up myself and have a PR out. Do you mind reviewing it? :) Also! Can you email join.ifme@gmail.com so we can add you to our Slack?

**Comment by mercyg** [comment]
I would be glad to review it :) But I am a newbie to open source project :) And I will email at the address. Thank you
