### ISSUE TITLE
Refresh LetsEncrypt in an automated way

### ISSUE THREAD

**Issue by nma** [julianguyen/ifme#421]
Our SSL CA, LetsEncypt while free only offers valid certs every 90 days. We will need a way to to refresh the certificate.

Proposal to use the following open source plugin to fix it for good:
1. Learning and adding a new Ruby plugin (https://github.com/pixielabs/letsencrypt-rails-heroku)

May require some https downtime during dev, so a push would be at off hours.
.

**Comment by nma** [comment]
Anyhow going to start this, assigned you just as a heads up

**Comment by julianguyen** [comment]
This is awesome thanks so much :D

**Comment by nma** [comment]
So it looks like this plugin will require embedding global Heroku oAuth Keys (to perform cert upload through the platform-api) in the deployed Environment.

So this means is, people who have been granted access to in the heroku app can see these oAuth keys. They can then impersonate your user with full access on this project, and all other projects your user is attached to. 

It is a bit iffy, but if your heroku user is only used for this project, and the folks with access to the deploy is limited, then its not a big issue.

**Comment by julianguyen** [comment]
Hmmm I think this should be fine. Definitely iffy though :/ Are there any alternatives? Thanks for looking into this @nma!

**Comment by nma** [comment]
Actually, we can create another account, and just give it restricted permissions. e.g. (infrastructure@if-me.org)

**Comment by nma** [comment]
Heroku beat us to the punch. 
https://devcenter.heroku.com/articles/automated-certificate-management

Now you can check the app by `heroku certs:auto` if you are an admin. I'll open a PR to remove our old way of adding certs.

The root domain,  `if-me.org` is failing, so something to take a look at on your end @julianguyen? Something about DNS configurations.
