### ISSUE TITLE
Invite multiple people by email

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#424]
Currently, users can only invite one person a time by email. We want to add the ability to add multiple emails that are comma separated (including comma-space separated).

Current behaviour:
![image](https://cloud.githubusercontent.com/assets/3010728/23581658/b53c321c-00cc-11e7-9803-67a659649da4.png)

**Comment by nehalita** [comment]
@julianguyen I'll try this one!

**Comment by liirene1** [comment]
Note: This issue has a prerequisite before completing this task: Devise knowledge required. You have to override the Devise authentication.

**Comment by liirene1** [comment]
To see this component on localhost: 
1. Click **Sign In** on header
2. use the test username and passwords in the _seeds.rb_ file 
3. Click **Allies** on header 
4. Click Invite **Your Loved Ones** 

http://localhost:3000/users/invitation/new

<img width="585" alt="screen shot 2017-03-22 at 10 38 08 pm" src="https://cloud.githubusercontent.com/assets/16128022/24233560/497af062-0f50-11e7-85ef-e6207c59c392.png">

**Comment by logeshmallow** [comment]
I can add the multiple email invite provision. Can I take that and send you the pull request?

**Comment by julianguyen** [comment]
Hi @logeshmallow! Feel free to work on it and make a PR!

**Comment by julianguyen** [comment]
Thank you

**Comment by julianguyen** [comment]
@logeshmallow How is this going?

**Comment by logeshmallow** [comment]
@julianguyen I have worked on it and I will try to complete it by this weekend and send you PR.

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Invite multiple people by email](https://trello.com/c/kKFi5Xqh/23-3-invite-multiple-people-by-email)

**Comment by haleymnatz** [comment]
@julianguyen I'd like to give this a shot if that's alright!
