### ISSUE TITLE
Ability to close modals with ESC key and clicking the backdrop

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#429]
![wsc_opensourcehours](https://cloud.githubusercontent.com/assets/3010728/24170861/8127b1ba-0e3f-11e7-8b0b-dcfe8661b3b9.png)

<img width="1105" alt="screen shot 2017-03-21 at 10 53 26 pm" src="https://cloud.githubusercontent.com/assets/3010728/24184060/3d094044-0e89-11e7-860c-b066aaa8e173.png">

Currently, the user can only close the modal by hitting the X button. We want to add the ability to close the modal using the ESC key and by clicking the backdrop i.e. area outside of the modal.

**Comment by evykassirer** [comment]
@clairewild and I made some progress https://github.com/julianguyen/ifme/compare/master...evykassirer:closing_modals?expand=1

still missing:

- a few modals (e.g. Moments -> Anxious)
- using escape on some of the modals in Moments/Strategies (at least one works though)
- using escape on the homepage modal

But progress is being made! I might work more on this, but if anyone wants to copy my diff and keep working go for it :)

**Comment by clairewild** [comment]
https://github.com/clairewild/ifme/blob/master/app/assets/javascripts/notifications.js

Have been working on this and as far as I can tell it works for all the modals.
