### ISSUE TITLE
Add internationalization support for Brazilian Portuguese

### ISSUE THREAD

**Issue by ThePedroPaulino** [julianguyen/ifme#453]
I`ll be working on the Brazilian translate version of Ifme. Do not mistake Brazilian Portuguese with just Portuguese: The first one we speak in Brazil, and the second one is spoken in Portugal. Some words have different meanings , but in general, both countries can understand each other.

**Comment by igorcap** [comment]
Hi. This is my first time collaborating in a open source project but I'm Brazilian as well and I was thinking about doing the same thing, so if you need any help I will be happy to assist you.

**Comment by ThePedroPaulino** [comment]
Hello Igor, welcome to If-me. If you have any questions regarding the translation, please ping me. I worked with the translation and any feedback or improvements will be appreciated. Did you manage to fork the repository and running locally the application ?

**Comment by julianguyen** [comment]
Hi @igorcap we would love for you to contribute! Can you send as an email join.ifme@gmail.com so we can add you to our Slack, and we can chat more? :D Thank you ^^
