### ISSUE TITLE
Secret share Moments

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#455]
The ability to share secret links to your Moments posts so that non if me users can view them! Sometimes people don't like creating new accounts. Or you want to have a discussion about something off the platform.

**Comment by SophieRoseMcDonald** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Secret Share Moments](https://trello.com/c/jpYBcg0c/27-3-secret-share-moments)

**Comment by andy5995** [comment]
This was included with #623 ? Ready to be closed?

**Comment by HashNotAdam** [comment]
Thanks, @andy5995, we should have closed this already

**Comment by HashNotAdam** [comment]
Thanks, @andy5995, we should have closed this already
