### ISSUE TITLE
Update app from Rails 4.2.6 to Rails 5

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#456]

**Comment by HashNotAdam** [comment]
I'd be happy to help out with this one.
Is the plan to get to 5.1 (via 5.0)?
Any known issues that could make it tricky?

**Comment by julianguyen** [comment]
@HashNotAdam Yeah I think getting it to 5.0 is a good start then 5.1 will be more straightforward. Do you think just upgrading to 5.1 is fine? There are no known issues!

**Comment by HashNotAdam** [comment]
It will most likely be completely fine to produce a PR to goes straight to 5.1 but I'll do the update in two steps and just only submit the final position. There will need to be changes to things like Selenium and the documentation regarding Firefox so I think it's better if the community only sees one change there.
