### ISSUE TITLE
Use cases and HIPAA compliance?

### ISSUE THREAD

**Issue by chriswingler** [julianguyen/ifme#46]
Hey I'm currently in therapy after years of homelessness and mental illness and since I'm interested in technology, my therapist and I have been talking about how we might be able to include technology in our sessions.  I've brought my laptop in and showed her cool stuff like Github, Cloud9, IBM's Bluemix, and Trello and I plan on showing her If Me in our next session, but at first glance I'm assuming she'll see it mostly as a cool idea at this point but maybe even *yet another software she'll have to deal with.*

So how can she see it as something we need to be using right away?

Anyway, personally, and as a mental heath patient, I can't stand talking about my triggers and moods, but the strategies and groups sections interest to me.  I would love to click on strategies and see proven strategies for overcoming addiction, or getting out of homelessness, or depression, or etc etc and then be able to network with people and talk about it with both peers and professionals in the session.  Something like like a virtual "crisis house" with advanced technology would be really cool.

Also, are you guys HIPAA compliant?  That's a huge issue to us and a big reason why we couldn't use something like Google Docs because they track all your keywords and browsing history and whatnot and sell it to marketers and advertising companies.  So, we're talking about using military grade encryption to cover our sessions.

Anyway If Me looks cool.  I may end up contributing in some fashion and hope to hear back from you!

- Chris

**Comment by julianguyen** [comment]
Thank you Chris for taking the time to write us and open up. We are not HIPAA compliant and thank you for brining that up! Could you email us at join.ifme@gmail.com? We'll add you to your Slack page and schedule a time to video chat!

We're aiming to launch the beta version by the end of year and have MH patients and practitioners give their feedback! We also want to get feedback before that!
