### ISSUE TITLE
Content Changes to ifme

### ISSUE THREAD

**Issue by WWLChen** [julianguyen/ifme#461]
Text changes that are additions are in parenthesis (add) and deletions are in brackets [delete] and +++comments+++  are comments and/or questions.
--------------------------------
URL: https://www.if-me.org/about

- [ ] replace if me with if me - stylized version with color
- [x] Our app is a completely open source (project). It's built and maintained by volunteers of many different backgrounds and skill sets.

URL: https://www.if-me.org/contributors

- [ ] replace if me with if me - stylized version with color

URL: https://www.if-me.org/faq

- [x] Data is not given or made accessible (to) any third party. 
- [ ] You can tag [it] (Memories) with Strategies, Categories, and Moods. You can also choose which allies can view and comment. You can also make [it] (Memories)  only visible to you
- [x] A Strategy is an activity, train of thought, or form [or] (of) self-care
- [x] You can tag [it] (Memories) with Categories. You can also choose which allies can view and comment. You can also make [it] (Memories) only visible to you. Shared Strategies will be visible to all allies specified, which means you can tag your Moments with their Strategies!
- [x] Go to the Account page by hitting  desktop or mobile in the navigation bar. You can modify your email, password, profile picture, and bio here. You can also delete your account. (Once you delete your account, all your data is deleted. ) +++And any messaging that clarifies what happens when you delete your account, and should this have a separate heading of "Delete Account"?+++

**Comment by indicatz** [comment]
Hey, I'm a newbie. Would you recommend this issue for a beginner?

**Comment by julianguyen** [comment]
@indicatz yes, go right ahead!

**Comment by kavixiu** [comment]
Hi! Is anyone currently working on this? I'm another interested newbie

**Comment by julianguyen** [comment]
@kavixiu Not that I know of, feel free to take it and assign yourself to it!

**Comment by kavixiu** [comment]
Thanks! Pull request submitted :)
