### ISSUE TITLE
Cookies not being cleared properly in toggle_language_spec.rb causing flakey Circle CI test failures

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#472]
We've been getting a lot of flakey test failures from Circle CI because of [toggle_langauge_spec.rb](https://github.com/julianguyen/ifme/blob/master/spec/features/toggle_language_spec.rb) and cookies not being [cleared](https://github.com/julianguyen/ifme/blob/master/spec/features/toggle_language_spec.rb#L4). Cookies should be clearing after each test.

I need some help fixing this up so that the tests related to language toggle reliably pass.

**Comment by HashNotAdam** [comment]
Is _that_ what that is‽ 😆

**Comment by julianguyen** [comment]
I tried to fix it and I think it works? Gonna keep this issue open for a bit longer to confirm!
