### ISSUE TITLE
Memory quota errors on Heroku

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#479]
Been getting a lot of these errors lately from production
```
ifme heroku/web.1: Error R14 (Memory quota exceeded)
```

Looks like this [guide](https://devcenter.heroku.com/articles/ruby-memory-use) will help solve our problems!

**Comment by HashNotAdam** [comment]
Have you taken a look at the memory usage chart? Does it gradually rise or shoot up? Is the memory initially low and then grows or near max from the start?

Freezing the string literals will have a small advantage but I doubt it will completely fix this issue.

**Comment by julianguyen** [comment]
It looks like it shoots up
![image](https://user-images.githubusercontent.com/3010728/27886764-563a4692-6192-11e7-90ec-13db6f5d1b43.png)

**Comment by HashNotAdam** [comment]
I would expect a minor drop in memory use now, is this reflected in the charts?

**Comment by julianguyen** [comment]
Looks like this now
![image](https://user-images.githubusercontent.com/3010728/27979205-feb43c50-6328-11e7-9420-e5bfc7d0a12e.png)

**Comment by HashNotAdam** [comment]
While that looks great, I think those deployments are getting in the way of the memory hitting max. Will be good to see what happens if there are no new deployments.
