### ISSUE TITLE
Medications example: mixed up fields

### ISSUE THREAD

**Issue by shelleyvadams** [julianguyen/ifme#482]
In the Prozac example that's displayed on a new user's Medications page, the "Total" and "Daily Dosage" fields appear to be mixed up:

> Total: 2 tablets
> Daily Dosage: 40 tablets

Probably an easy fix. :grin:

**Comment by julianguyen** [comment]
OMG awesome find @shelleyvadams, thank you! :D Would you be interested in fixing it?

**Comment by shelleyvadams** [comment]
Maybe... Need to get a web server running again first.

Last week I upgraded/broke my development environment. This week I've been digging through documentation and reminding myself that I have a very recent backup.

**Comment by julianguyen** [comment]
@shelleyvadams Ah no problem! I can quickly fix this then :)

Can you send us an email at join.ifme@gmail.com so that I can you to our Slack? :D We can help you more with your dev environment :)
