### ISSUE TITLE
Write unit test to check that the translation files do not have missing keys

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#491]
This will automate determining whether we are missing translation keys across all of our yml files!

This looks like a promising route to take: http://blog.kiskolabs.com/post/908453942/comparing-rails-locale-files-for-missing

**Comment by SophieRoseMcDonald** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write unit test to check that the translation files do not have missing keys #491](https://trello.com/c/tgMZ3Sz5/58-write-unit-test-to-check-that-the-translation-files-do-not-have-missing-keys-491)
