### ISSUE TITLE
Medications page is blank after submitting new medication

### ISSUE THREAD

**Issue by shelleyvadams** [julianguyen/ifme#499]
I got a blank page after I submitted information the New Medication form.

I had entered content only in the required fields (i.e., no comments) and did not mark any of the checkboxes.

The page remains blank when I reload it, but displays properly when I request the page from the address bar (Ctrl+L, Enter). It also appears that a duplicate medication was created when I tried to reload the page.

Using Firefox ESR 52.2.0 (64-bit)

**Comment by julianguyen** [comment]
This is happening for me on a Google authenticated account

```
Jul 18 20:11:19 ifme app/web.1: Google::APIClient::AuthorizationError (Invalid Credentials): 
Jul 18 20:11:19 ifme app/web.1:   app/services/calendar_uploader.rb:34:in `upload_event' 
Jul 18 20:11:19 ifme app/web.1:   app/controllers/medications_controller.rb:97:in `save_refill_to_google_calendar' 
Jul 18 20:11:19 ifme app/web.1:   app/controllers/medications_controller.rb:56:in `block in create' 
Jul 18 20:11:19 ifme app/web.1:   app/controllers/medications_controller.rb:54:in `create' 
Jul 18 20:11:19 ifme app/web.1:   app/controllers/application_controller.rb:31:in `block in with_timezone' 
Jul 18 20:11:19 ifme app/web.1:   app/controllers/application_controller.rb:31:in `with_timezone' 
```

**Comment by julianguyen** [comment]
@shelleyvadams Did you encounter this bug on your local dev environment or on production?

**Comment by julianguyen** [comment]
Hmm things seem to be working for me now...

**Comment by shelleyvadams** [comment]
It's happening in production. I'm also using a Google authenticated account.

I just tried it with the test1 user in my dev setup. That behaved _very_ differently. After submitting the form it loads the page for the medication I just added -- e.g., `/medications/testmed` -- whereas the production system displays a blank page (with no source) at `/medications`.

**Comment by shelleyvadams** [comment]
Two new observations:
1. When I add a medication _immediately_ after I sign in, it works correctly. No blank screen. (I'd been logged in for quite a while when I got the blank screen when adding medications.)
2. A refill reminder **is added** to my Google Calendar even when the checkbox for "Google calendar reminder" is **not checked**. (I'll create a separate issue for this shortly.)

The log message `Google::APIClient::AuthorizationError (Invalid Credentials)` probably holds the key.

Still reading through docs and code to figure things out, but it seems that authentication for Google Calendar is timing out much earlier than the authentication to use if me.

**Comment by shelleyvadams** [comment]
I've reproduced the problem locally. 

The [attached log](https://github.com/julianguyen/ifme/files/1166267/if_me_log-20170721.txt) contains two server runs.

1. **Lines 1-788.** Includes successfully adding two medications (Tylenol and Asprin).
Tylenol was added 2-3 minutes after Google authenticated sign-in; POST begins at line 414.
Asprin was added almost 1 hour after the same sign-in; POST (Asprin) begins at line 560.
2. **Lines 789-966.** Includes adding a medication (Tylenol) that generated an error, approximately 17 1/2 hours after Google-authenticated sign-in. POST begins at line 945.

**Comment by abrophy** [comment]
I think you're right @shelleyvadams in that it's the token generated by google oauth that's expiring.

I've been looking around and it's recommended that we should treat all keys as being very short lived and requesting new ones regularly. I'm not yet familiar enough with the ifme determine where best to do this in the lifecycle though.

**Comment by shelleyvadams** [comment]
Unfortunately the tutorials I've worked through thus far have overlooked error handling, 🙁 but I assume there's something akin to a `try` and `catch` mechanism of Java and JavaScript. Seems like the most straightforward approach would be to watch for a possible `Google::APIClient::AuthorizationError` and refresh the access token when catching it.

@julianguyen said that we're using Devise for Google authentication. Hopefully, it stores the [reusable refresh token](https://developers.google.com/idesontity/protocols/OAuth2) for us.

**Comment by abrophy** [comment]
My first thought was to save the token expiration time to User, because the oauth response contains the expiration time as an epoch timestamp. We can then check if the token is expired by comparing that timestamp with current time.

However, it seems that the gem doesn't handle or request refresh tokens and we'll have to implement something similar to what's found in [this gist](https://gist.github.com/GregBaugues/276d7c13e9f7a28db010).

Shouldn't be too hard but it makes sense to follow the example set by that gist and make tokens their own model which belongs_to User, seeing as there'll be a bunch of lifecycle methods involved in checking if its expired and then updating it if it has.

What do you think of this plan, shall I create a new GoogleToken model? Or do you think its overkill to give it its own table and rather just store everything plus have the lifecycle methods on User.

**Comment by abrophy** [comment]
Actually it'll be quicker to just put the behavior in User model for now, we can always move it out into its own model/class later if we need to.

**Comment by julianguyen** [comment]
Sounds good to me! @abrophy
