### ISSUE TITLE
Medication refills added to Google Calendar when checkbox is not checked

### ISSUE THREAD

**Issue by shelleyvadams** [julianguyen/ifme#505]
When adding a medication, a refill event is added to Google calendar even when the checkbox for "Google calendar reminder" is **not** marked.

Also, when this checkbox is marked, its state is not retained in future edits.

**Comment by abrophy** [comment]
Hi, I'd like to attempt this one.

**Comment by shelleyvadams** [comment]
I'm still getting up to speed with Ruby. Thanks for tackling this @abrophy! 😁
