### ISSUE TITLE
Fonts for i18n

### ISSUE THREAD

**Issue by baohouse** [julianguyen/ifme#525]
Lato is currently the site's main font, however, it's better to use the system font of the operating system to better support i18n. See https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/

Otherwise, as in the case of Vietnamese language, Lato's support for that language falls short.
<img width="446" alt="screen shot 2017-07-31 at 7 05 00 pm" src="https://user-images.githubusercontent.com/4228012/28802572-19c23c04-7625-11e7-965c-d657d6571f18.png">

**Comment by baohouse** [comment]
I'm going to make a PR... so it will be:
San Francisco for OS X versions that support it, fallback to
Segoe UI for Windows that support it, fallback to
Roboto (import via Google Font), and finally sans-serif.

I know for sure that San Francisco, Segoe UI, and Roboto have weight 300 for their fonts, which I seem to see in use throughout the application.

**Comment by julianguyen** [comment]
Wow, such a great point. Thanks for bringing this up Bao :D

**Comment by baohouse** [comment]
#526 is a PR to update Lato to version 2.0, which has far better support for Latin-based languages. We'll leave this issue open to better discuss what the architecture should be to support non-Latin languages, e.g. Chinese, Japanese, Thai, Arabic, etc.
