### ISSUE TITLE
Missing categories_controller_spec.rb and moods_controller_spec.rb

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#534]
We're missing specs! Ahh!

**Comment by timorthi** [comment]
I'd like to work on this! :)

**Comment by julianguyen** [comment]
@timorthi Yeah feel free to take this issue! Adding you as a collaborator to this repo so I can assign it to you. Also can you email join.ifme@gmail.com so we can add you to our Slack? Thanks!

**Comment by timorthi** [comment]
Oops, I guess I should only be referencing the issue in the PR to avoid the commit spam. My bad!

**Comment by julianguyen** [comment]
Woo thanks for working on this @timorthi :D
