### ISSUE TITLE
Open CKEditor in full-screen on mobile web

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#538]
It's can be difficult to enter content in the Moments/Strategy form on mobile web because the on-screen keyboard covers most of the page.

Desired behaviour:
1) User clicks the CKEditor
2) Full-screen modal opens with just the CKEditor for that input field
3) User types in content
4) When they hit the "x" icon, the text they wrote to the editor appears in form

![image](https://user-images.githubusercontent.com/3010728/29186652-ff6253a4-7dc1-11e7-9857-1e137905b33a.png)

**Comment by alvarocasadoc** [comment]
I would like to help with this issue. I've been checking the code on the repo and I think I could try tackling this one.

**Comment by alvarocasadoc** [comment]
I think maybe something like this would do well: 

Current behaviour:

- **Only** when the viewport is small enough (**< 640px**).
- User taps one of the ckeditors and a **new modal** is displayed with a ckeditor inside. This modal is implemented as a new **partial** (`views/shared/_editor_modal`) and it is included in `views/moments/_form` and `views/strategies/_form`.
- **While this modal is visible, page scrolling is disabled** to improve usability by leaving only the ckeditor field's scroll active.
- This editor has the **same contents** from the selected ckeditor.
- When the user taps the closing cross icon the modal disappears and the content appears in the previously selected ckeditor and **page scrolling is re-enabled**.
- Form is submitted and its contents are saved.

This behaviour is coded in `assets/javascripts/mobile_cke.js` and the styling is inside `assets/stylesheets/editor_modal.scss`.

I've also started writing some tests in `spec/javascripts/modal_editor.js`.

Next:
- I would like to know if there is any special styling guideline to follow with this one and if there is something more to do or change for this issue.


Here's a little demo:

![demo0](https://user-images.githubusercontent.com/7248474/31047240-14f63c72-a607-11e7-9445-6a6390ed82a5.gif)
