### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#54]
I'm currently working on the privacy policy and am looking for help to write it!
Things we want to outline:
* What data is being collected
* How the data will be used
* How the data will be protected in all circumstances

**Comment by markfarrell** [comment]
Privacy policy can be found at http://www.if-me.org/privacy now?

**Comment by markfarrell** [comment]
Wait, but how will user data be protected?

**Comment by julianguyen** [comment]
Good question: not sure how to phrase that. Ideally, we will not be giving user data to third parties including government, police, or medical organizations without the user's consent.

**Comment by julianguyen** [comment]
Not sure if we are allowed to explicitly state that or if that requires some kind of legal intervention (see: https://github.com/julianguyen/ifme/issues/46)

**Comment by markfarrell** [comment]
Is one of the project goals to become HIPAA compliant?

**Comment by julianguyen** [comment]
@markfarrell I think so. But I honestly do not know the process for being HIPAA compliant. We definitely need help with this!
