### ISSUE TITLE
Add messaging that says no search results found for Allies page

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#543]
Currently, the page looks like this when no results are found:
![image](https://user-images.githubusercontent.com/3010728/29346942-b6dba0be-81fd-11e7-8fc2-80ae842a6085.png)

Let's add some messaging to the body that says "User not found", be sure to translate this into Spanish and Portuguese too :)

**Comment by geoninja** [comment]
@julianguyen @katrynmc This would be "usuário não encontrado" in Portuguese.
