### ISSUE TITLE
Comments should have polymorphic relationships

### ISSUE THREAD

**Issue by HashNotAdam** [julianguyen/ifme#547]
Many models have many comments however this relationship is being manually maintained by commented_on and comment_type instead of simply using an ActiveRecord polymorphic relationship.

**Comment by slauppy** [comment]
Looking through the tests, these models already support comments:
- meetings
- strategies
- moments

Are there any I'm missing?

**Comment by HashNotAdam** [comment]
@slauppy these are the only ones I've encountered.
