### ISSUE TITLE
Has anyone enquired about cost of getting if.me?

### ISSUE THREAD

**Issue by pederjohnsen** [julianguyen/ifme#553]
Out of interest, has any of you enquired about the cost of getting http://if.me?

**Comment by julianguyen** [comment]
Yes, I have lol... It's like thousands of dollars and you need to prove you're a legit business.

**Comment by pederjohnsen** [comment]
Yeah that's a bit over the top... Granted if I ever win the lottery, I'd gladly donate the money towards it :joy:

I'll close the issue to prevent it from taking up important space for more important issues :)
