### ISSUE TITLE
Create helper method to handle redirects in controllers

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#564]
There is **a lot** of controller code that looks like this
```
respond_to do |format|
  format.html { redirect_to moods_path }
  format.json { head :no_content }
end
```

To minimize on code repetition, it would be great to call a single helper method and perhaps pass in the desired path as an argument.

**Comment by camillevilla** [comment]
@julianguyen I found a method `redirect_to_path` in `app/controllers/application_controller.rb:333`. I did a lil' refactor in the categories controller, ran the tests, and it seems to work! Would it be cool if I start working on a PR?

**Comment by julianguyen** [comment]
@camillevilla Heck yes! Assign yourself to the issue once you get added as a collaborator :D
