### ISSUE TITLE
Putting string labels in en.yml

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#58]
Ideally, string labels (used in forms, headings, etc.) should be placed in config file so that we can easily modify things in the future. Go through all of the strings being used in the various views and put them in en.yml

**Comment by bellawoo** [comment]
Hi,

I've already got a copy running and have starting working on this. Would you like to assign to me?

Thanks!
Bella

**Comment by julianguyen** [comment]
@bellawoo That would be awesome! Thanks Bella!
