### ISSUE TITLE
Issue in setting password for invited users

### ISSUE THREAD

**Issue by charlesskariah** [julianguyen/ifme#584]
I have invited a user using the email and when i tried to follow the link via email and found that there is only field for password.After setting the password it shows name can't be blank validation error. I think there isn't any option for invited users to add name since name is mandatory as well

**Comment by charlesskariah** [comment]
![ifmebug](https://user-images.githubusercontent.com/8168093/29870842-1a9f1dec-8da7-11e7-8acd-386f83ef59fd.png)
I checked over the development enivironment and it seems to be not working.Attaching the screenshot of the page and I think adding a name field on the confirmation page while  setting password would solve the problem.

**Comment by charlesskariah** [comment]
@baohouse  What do you suggest for this bug?Options are 

1. Adding a name field when inviting.
2. Adding name field when setting password
What do you suggest?I can raise a PR once confirmed.

**Comment by baohouse** [comment]
Hi @charlesskariah! Go ahead and email join.ifme@gmail.com and you'll be invited to the Slack channel. I posted in the #bugs channel there if anyone knows how invitation is supposed to work (whether name should be required or not), since I'm not familiar with the entire product as of yet.

**Comment by alexiamcdonald** [comment]
Hey @charlesskariah after having a quick look at the controller I can see that `name` or something similar perhaps `user` needs to be set in params which don't exist yet.

The controller needs a bit of a refactor to allow for this.

Let me know if you need any help or want to work on this together.

**Comment by charlesskariah** [comment]
@alexiamcdonald I will raise a PR with necessary changes and please let me know your thoughts after that.

**Comment by alexiamcdonald** [comment]
@charlesskariah awesome! Good luck. Can't wait to see it. 😄

**Comment by charlesskariah** [comment]
@baohouse Thanks for the update

**Comment by charlesskariah** [comment]
I was going through the issue and it seems like working without any fixes.Weird !!. @alexiamcdonald Can you please try to reproduce that issue.?

**Comment by alexiamcdonald** [comment]
@charlesskariah Yeah I'll have a look 😄

**Comment by alexiamcdonald** [comment]
@charlesskariah I've had a look.

**Long answer:** There is a bunch of work that needs to be done under the hood. But for now we should leave it as is as the more pressing matter is that if the user doesn't have a name they won't be able to reset their password or sign in.

**Short answer:** The correct solution for now is to add name to the form so user can add name as @julianguyen and @baohouse have said.

**Comment by julianguyen** [comment]
Fixed this by adding a name field to the accept invitation form!
