### ISSUE TITLE
RSS or Atom feed for blog

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#592]
I wanted to suggest adding an RSS or Atom feed for [the blog](https://www.if-me.org/blog)

**Comment by baohouse** [comment]
The blog is syndicated from Medium https://medium.com/ifme, so would we just add that feed on the if-me.org's header for now?

**Comment by andy5995** [comment]
I've assigned this issue to me. Would that be a matter of just adding something like `<link id="feedLink" rel="alternate" type="application/rss+xml" title="RSS" href="https://medium.com/feed/ifme">` to the header?

And would we also want a small RSS icon on the footer, with a link to the feed?

**Comment by julianguyen** [comment]
I think that is correct @andy5995!

**Comment by andy5995** [comment]
The location of the text link for the feed? How about underneath the _Email_ link in the _Connect_ section of the footer?

**Comment by andy5995** [comment]
One problem that may derail this patch as is:

Clicking a link in the feed takes the user to the Medium/if me page, therefore a regular if-me.org sign-in won't work. Could be confusing to people.

I'd like to hear more discussion about this before I proceed with #611 

But I'm not in any hurry. ;)

**Comment by baohouse** [comment]
If we click on an article via the if-me.org blog, it takes us to the Medium post already. I do agree that from a UX perspective, it's a source of confusion. Adding a warning "You're about to leave this site to enter another" is standard practice, but definitely not ideal. _Perhaps_ having the blog exist entirely on the if-me.org site might be a solution, but that's way beyond the scope of what you want to achieve with this issue. So I think #611 is fine for now until we figure out a more UX-optimal solution for the blog feature in general.

**Comment by desirottman** [comment]
Medium does allow for custom domain usage, but there is a setup fee: https://help.medium.com/hc/en-us/articles/115005579728-Get-started-with-custom-domains
