### ISSUE TITLE
Change text displayed for users with 0 groups

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#606]
[![Screenshot_2017-09-07_21-43-59.png](https://s26.postimg.org/pkqcaigax/Screenshot_2017-09-07_21-43-59.png)](https://postimg.org/image/b1j793n5x/)

me:
> 
> As a new user, I found this confusing: "You aren't a part of any groups yet! Click to create one or join any available groups below." The confusion was that there were no groups listed, but directly underneath the "Connect" menu is shown with all the social networks. So I thought, am I being directed to join _those_ groups? I realized "no". So there is some feedback from a new user perspective
> 
> Perhaps in this case, there should be a message under that first line that states something like "0 groups found" ? 

julianguyen:

> Hmmm yeah that could be a good improvement to indicate none exist between you and your allies.

hashnotadam:

> Or, if there are not groups, don't show "or join any available group below"?

tmoore:

> Maybe even a little instruction text about what groups are and how to create or find them.

**Comment by andy5995** [comment]
TODO

1. Decide on text to display when there are 0 groups
2. Decide on text to display when there are 1+ groups
3. Decide on common text that will display in both cases 1 & 2

Also, I think this existing message should be changed:

> Click + to create one or join any available groups below.

The image/+ sign in that sentence is not a clickable link. So I'd suggest something like

> Click +  (icon in upper right corner) to create one or join any available groups below.

But that seems a bit clunky to me. Is there any reason the small "+" icon (in the first sentence) isn't already linked to create a new group?

@desirottman For 1-3, we can discuss this a bit on Slack. I'm guessing we'll want some feedback from others at some point.

**Comment by desirottman** [comment]
I think the first thing to do is to define what a group is, so maybe under the "Create and join groups that offer support, mentorship, and discussions." title, we could say something like "**What is a Group?** A group is a space for you and your Allies to communicate. Support groups are great for having open discussions about mental health! You can create groups, invite members, and organize meetup events online or offline. You can also join groups your allies have created."

1. Then under that, I would add the "You aren't a part of any groups yet! Click + to create one with your connected Allies, or join any available groups below." language (edited a bit more there too). 
2. Text for 1+ groups: "Choose the group you would like to check in with. You can also click + to create one with your connected Allies, or join any available groups below."
3. Kind of the idea I mentioned above - let's start there and suss that out!

**Comment by andy5995** [comment]
Now I see there's already info about groups on the [FAQ](https://www.if-me.org/faq). We should link to that (in place of a group description) and not have that text duplicated on the _Groups_ page, imo.

To that end, If @julianguyen has no objection, we can add an [id attribute](https://www.w3schools.com/tags/att_global_id.asp) to the _groups_ heading on the FAQ page ([L372](https://github.com/julianguyen/ifme/blob/e22f7914a26a8c97e963cecd2e8e3a9d90097084/config/locales/en.yml#L372)).
