### ISSUE TITLE
Issue setting up development environment in local after pulling latest master

### ISSUE THREAD

**Issue by charlesskariah** [julianguyen/ifme#627]
Rails server is running and when i tried to load the url in browser, I am getting the following error,

```
Error during failsafe response: 
        WebpackerLite can't find the manifest file: /home/charlesskariah/ifme/public/webpack/development/manifest.json
        Possible causes:
          1. You have not invoked webpack.
          2. You have misconfigured WebpackerLite's config/webpacker_lite.yml file.
          3. Your Webpack configuration is not creating a manifest.
```
This was working fine with my master before.This is happening after pulling the latest master.

**Comment by andy5995** [comment]
@charlesskariah this issue was just reported in #setup on Slack. Did you receive your invite yet?

**Comment by alexiamcdonald** [comment]
@charlesskariah I've run into this problem. I will investigate on my end. But if you figure out something in the mean time please let me know.

**Comment by charlesskariah** [comment]
@andy5995 I just found that invitaion email.My bad
@alexiamcdonald Will let you know if i came across a solution

**Comment by andy5995** [comment]
Ah... well, someone else has run into this problem too. It's being discussed in #setup.

**Comment by baohouse** [comment]
#626 is addressing this. For the time being, from the project folder,

```
cd client && yarn install
```

**Comment by alexiamcdonald** [comment]
Make sure you use the homebrew yarn and you have updated homebrew

**Comment by alexiamcdonald** [comment]
Running `foreman start -f Procfile.dev` instead of `rails s` fixes this issue. I've updated the readme. I'm closing this issue now as I believe it's solved.

**Comment by yasirazgar** [comment]
I have tried all the above steps
1. on running` yarn install and rails s`, i am getting
```
Error during failsafe response:
        WebpackerLite can't find the manifest file: /Users/yasirazgar/git/ifme/public/webpack/development/manifest.json
        Possible causes:
          1. You have not invoked webpack.
          2. You have misconfigured WebpackerLite's config/webpacker_lite.yml file.
          3. Your Webpack configuration is not creating a manifest.
```

2. on running `foreman start -f Procfile.dev`, I get,
```
12:52:16 web.1    | started with pid 86329
12:52:16 client.1 | started with pid 86330
12:52:16 client.1 | sh: bin/client.sh: /bin/sh^M: bad interpreter: No such file or directory
12:52:16 client.1 | exited with code 126
12:52:16 system   | sending SIGTERM to all processes
12:52:16 web.1    | terminated by SIGTERM
```

Need some help.

**Comment by yasirazgar** [comment]
Changing the line endings to unix, fixed the issue for me.
Ref: https://stackoverflow.com/a/23202386
