### ISSUE TITLE
"It's all in your head" : Wording on About page could easily be misinterpreted

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#629]
https://github.com/julianguyen/ifme/blob/bc657e1d31eea69cfe8287b6dfdaeb49ca193a25/config/locales/en.yml#L345

IMO, Wording could be easily be misinterpreted.

Specifically:
`\"It's in your head, but it's also all around you.\"`

I'm new to the project, so I still can give viewpoints from a fresh, "new-user" perspective.

When I first read that, I was confused for a couple seconds.

But I know perfectly well what you mean by that, and don't have any problem with the message you want to convey. But my initial reaction reminded me of times I heard stuff like, "It's all in your head, just snap out of it."

I'm not particularly knowledgeable about other countries or cultures, but my experience growing up and living in the US is that the phrase "It's all in your head" is often used as a [colloquialism](https://en.wikipedia.org/wiki/Colloquialism) that implies things like, "You're imagining things", or "There's no real problem, you're just imagining it".

As I said, I understand how you meant this phrase, but a lot of people have heard "It's all in your head" used in very negative ways when trying to speak with family or friends about mental health issues (though perhaps less so in the past decade or two).

**Comment by julianguyen** [comment]
Ah yes, I am familiar with being negatively told that "it's all in your head". I wrote `It's in your head, but it's also all around you.` to almost reclaim the "it's all in your head" negativity and reframe it as more realistic and neutral.

That's interesting that you and potentially others could associate it with negativity. Hmm maybe we could keep the line, but preface it with "It's not just all in your head. It's in your head, but it's also all around you". 

Thoughts everyone?

**Comment by timorthi** [comment]
> "It's not just all in your head. It's in your head, but it's also all around you"

I like this!

**Comment by andy5995** [comment]
"It's not just all in your head, but also in your heart and soul, and in your past. Healing is in your present."

**Comment by tracypholmes** [comment]
Ohh...I like both of these rewrites.

**Comment by andy5995** [comment]
I forgot to acknowledge this:

@julianguyen wrote:

> to almost reclaim the "it's all in your head" negativity and reframe it as more realistic and neutral.

I had a feeling that was your intent. :)

**Comment by julianguyen** [comment]
Ooh I like yours @andy5995, very poetic sounding. How about we combine them and make it more concise. Thanks for the output everyone!

"It's not just all in your head, it's around you. We can heal together."

**Comment by andy5995** [comment]
Just let me know when the decision is finalized. I'll submit the PR. :)

**Comment by julianguyen** [comment]
@andy5995 Thanks for following up on this <3 Yeah let's stick with `"It's not just all in your head, it's around you. We can heal together."` :D

**Comment by andy5995** [comment]
@julianguyen are you sure you want to omit the the word "all" in the second part of the first sentence? Something doesn't sound right in your final quote. Sounds kind of "choppy" to me. I just want to double check with you.

> @andy5995 Thanks for following up on this <3 Yeah let's stick with "It's not just all in your head, it's around you. We can heal together." :D

"...it's _all_ around you..." ?

**Comment by julianguyen** [comment]
Sure I'm fine with "it's all around you". Thanks!

**Comment by andy5995** [comment]
Ok.. I'll get the new translations tomorrow. Consider the existing PR as wip.

**Comment by andy5995** [comment]
I appreciate your enthusiasm, @julianguyen  (:wink), but I hadn't quite finished it. I was updating the _all_ part of it (see last three comments), just waiting for the SV translation.

What you merged has the translations from before we decided to add _all_.

If it's decided that someone will refine it further, here are the up-to-date translations.

EN: It's not just all in your head, it's all around you. We can heal together.

BR: As questões relacionadas a saúde mental não estão apenas na sua mente, mas ao seu redor. E juntos, nós podemos resolvê-las.

ES: Nada está sólo en tu mente, está todo alrededor de ti. Podemos sanar juntos.

SV: ?

**Comment by julianguyen** [comment]
Oh shoot I'm sorry I didn't realize. Feel free to make another PR with the rest of the changes. Whoops!

**Comment by andy5995** [comment]
Julia, we all love you and forgive you always. :) Please remember that the next time _I_ make a mistake. :)
