### ISSUE TITLE
Sleep, nutrition, exercise, supplement intake, meditation time, etc?

### ISSUE THREAD

**Issue by markfarrell** [julianguyen/ifme#63]
Hey,

I feel like I'd want to somehow be able to measure and log my sleep schedule, nutritional content of diet, exercise vigor & time, supplement intake, meditation time, etc. when using ifme. When poking around the app, I almost feel as though I'd like to be able to compare these measures/log to my mood/trigger event at a nearest moment in time and derive strategies from there. Derive strategies and then hopefully be able to determine how effective they are/adjust them in sort of a circular way with the data/support. There's no way to really have these measures/logs in ifme right now, is there (and use them approximately as suggested)?

Just an idea I had when thinking about how I would want to use the app. Thoughts?

**Comment by sashaperigo** [comment]
I think this is a great idea! It would be interesting to also allow users to pull in data from FitBit or Apple Health if they already use either of those apps for sleep, diet, or exercise tracking.

**Comment by julianguyen** [comment]
@sashaperigo Yess that's a fabulous idea! Would you like to work on that once you're free? :P

**Comment by sashaperigo** [comment]
@julianguyen yeah that would be super fun for me! I will keep in touch with timing.
