### ISSUE TITLE
Put foreman start -f Procfile.dev into an alias

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#637]
Let's put `foreman start -f Procfile.dev` into some kind of alias like `start_app`
or see how we can have it integrate with `rails server`.

**Comment by julianguyen** [comment]
Looks like you're tackling this @andy5995 :P Thank youuuu a bunch!

**Comment by andy5995** [comment]
I realized I didn't know what I was doing and gave it up.

But I'll ask a bunch of questions, once I get the #setup complete.

I didn't quite understand what you meant. You want a ruby script with the foreman start line in it? Or there's somewhere to make an alias for that command?

I'm so unfamiliar with rails and ruby I don't really know how the site works yet, or which file I would put an alias into or how to integrate it with the rails server

**Comment by andy5995** [comment]
Ok, @julianguyen my current status is #640
