### ISSUE TITLE
Research in psychology?

### ISSUE THREAD

**Issue by markfarrell** [julianguyen/ifme#64]
Broadly speaking, what research in psychology might help provide ideas / give implicit suggestions about how to improve the design & functionality of ifme?

**Comment by julianguyen** [comment]
@markfarrell Having people in the mental health field looking at the app and providing feedback on UX.

**Comment by markfarrell** [comment]
:+1:

**Comment by jimmynames** [comment]
Hello all, someone who's had extensive experience in both mental health (as professional and service user) and mHealth (mobile health/health apps) myself and an old colleague (maybe) would be willing to help.. please provide me with research focal points and I'll draft something up in addition to looking over the UX :3

**Comment by hellocam** [comment]
Hi @jimmynames!  I'm doing UX research on the app and I'm putting together a list of people who'd be willing to do some user testing on the app.  Are you still up for testing the app and providing some insight?  If you are, please let me know where I can contact you.  Cheers. :)

**Comment by julianguyen** [comment]
Hey @jimmynames! Can you email us at join.ifme@gmail.com so we can add you to our Slack and you can continue the conversation with @hellocam? :) Thanks for reaching out!
