### ISSUE TITLE
add some anonymous stats to the footer

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#643]
Adding some basic statistics to the footer might help to make the site appear more "dynamic", and from both a user and geek perspective, it might be interesting.

Here are some (not so original) ideas.
1. Number of logged in users
2. Number of guests
3. Total Number of registered users
4. Registrations in the last week

Some numbers that would be unique to _if me_
1. Number of *Moments* filed in the last week/day/hour
2. Number of medications being taken monthly

What do we think of this idea?

**Comment by andy5995** [comment]
Ah, ok. If clutter is a concern, then perhaps you'd rather have a single "Stats" link on the About page. When clicked, a small pop-out window that displays the stats?

**Comment by julianguyen** [comment]
For privacy concerns, I don't think we should share the number of moments or medications. But I am comfortable with sharing the number of registered users. That should just be a sentence on the About page.

**Comment by andy5995** [comment]
Understood. I'm trying to scale back my time on the PC right now, so this ticket is wide open for anyone.

**Comment by julianguyen** [comment]
Cool, I can take this on. Thanks so much @andy5995 for all your dedication and hard work! Don't forget to get some rest too :)

**Comment by andy5995** [comment]
Yw. I will!

**Comment by julianguyen** [comment]
Will revisit this in the future, closing for now.
