### ISSUE TITLE
including brief license info to the top of source code files

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#644]
https://github.com/julianguyen/ifme/blob/a73f997a1613bbb10a2db3fbb97c41f820ade935/LICENSE.txt#L627

 Re: Including some brief blurb about license info at the top of source code files: I've noticed it's sometimes customary to do this with OSS projects. Would it be a good idea to include the info to any source code files that are changed from this point on? Quoted from L627 of the License:

> To do so, attach the following notices to the program.  It is safest
> to attach them to the **start of each source file** to most effectively
> state the exclusion of warranty; and each file should have at least
> the "copyright" line and a pointer to where the full notice is found.

>     <one line to give the program's name and a brief idea of what it does.>
>     Copyright (C) <year>  <name of author>
> 
>     This program is free software: you can redistribute it and/or modify
>     it under the terms of the GNU Affero General Public License as published
>     by the Free Software Foundation, either version 3 of the License, or
>     (at your option) any later version.
> 
>     This program is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU Affero General Public License for more details.
> 
>     You should have received a copy of the GNU Affero General Public License
>     along with this program.  If not, see <http://www.gnu.org/licenses/>.
> 

Also add information on how to contact you by electronic and paper mail.

**Comment by julianguyen** [comment]
This is a good suggestion, but it feels burdensome to add this to every file. Also, we aren't written code that is going to be reused in a library or anything like that. I think it will suffice to have our OSS license mentioned on our site and the licensing section on the repo page. Thanks for bringing this up!

**Comment by andy5995** [comment]
Understood! :)
