### ISSUE TITLE
Splitting the README

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#650]
Should the installation instructions be moved into INSTALL.md file?
Should anything related to contributing be moved into CONTRIBUTING.md?

Would that make it easier to edit, proofread, and maintain the files?

If that were done, It looks like not many links would have to updated:
```
~/src/ifme$ ack "README.md"
CONTRIBUTING.md
46:Please check out our [README](https://github.com/julianguyen/ifme/blob/master/README.md) for step-by-step instructions on how to setup up our Ruby on Rails app locally.
49:* [Testing Guidelines](https://github.com/julianguyen/ifme/blob/master/README.md#testing-guidelines)
50:* [Committing Work](https://github.com/julianguyen/ifme/blob/master/README.md#committing-work)
51:* [Tracking Issues](https://github.com/julianguyen/ifme/blob/master/README.md#tracking-issues)

```

though some links on the wiki would also need to be updated.

**Comment by andy5995** [comment]
If this ticket gets approved, and after my Slack account is reactivated, I'd like to work on this.

**Comment by dippersauce** [comment]
I'd like to help you with this when Hacktoberfest kicks off. Would you mind posting your slack?

**Comment by julianguyen** [comment]
Hey @dippersauce, can you email join.ifme@gmail.com so we can add you? Let's chat more there on the specs. Thanks :)
