### ISSUE TITLE
Handle overflow text in most_focus module

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#662]
![image](https://user-images.githubusercontent.com/3010728/30840087-2e6662c6-a22a-11e7-9183-64be7e6546ec.png)

Hmm how should we handle this case?

**Comment by faraazahmad** [comment]
I can implement a bootstrap grid, that is, if you're using bootstrap

**Comment by faraazahmad** [comment]
![screenshot from 2017-09-29 17-57-06](https://user-images.githubusercontent.com/19265077/31015840-afc9cf98-a53f-11e7-9929-195d0b45bcd4.png)

Has it already been solved?

**Comment by julianguyen** [comment]
@faraazahmad Nope. So to see that stats you need to tag your Moments posts with Strategies then it'll appear! :) Also please email us at join.ifme@gmail.com and I'll add you to our Slack!

RE: bootstrap grid, I personally don't want to use it cause it's bulky. We could import only what we need, but I believe we can easily implement this ourselves with flex boxes.

**Comment by colelabar** [comment]
You are referring to the overflow categories at the bottom of the first image, correct? I can give this a go using FlexBox, I'll fork it and let you know how it goes!
