### ISSUE TITLE
Support pry logging with foreman

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#667]

**Comment by andy5995** [comment]
I looked at a couple links to do this but couldn't figure it out. Here they are for reference:

pry/pry#1290

https://stackoverflow.com/questions/32671250/is-there-a-reliable-tool-for-stepping-through-code-while-serving-in-foreman

**Comment by andy5995** [comment]
I tried the instructions at https://groups.google.com/forum/#!topic/foreman-dev/oLyjl8YNv2A

but don't know what the equivalent of "server.rb" would be to trigger pry

>  Add a line to trigger pry (/usr/share/foreman/app/models/concerns/fog_extensions/vsphere/server.rb)
> binding.pry
>

**Comment by julianguyen** [comment]
Thanks for looking into this @andy5995! @SophieRoseMcDonald and @jnamster have a solution https://github.com/julianguyen/ifme/pull/672. Feel free to weigh in!
