### ISSUE TITLE
navigation to "help" may need adjustment

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#668]
So I go to if-me.org...

There's a link if I want to "help" the project.

After logging in, no link for "help".

There's not one on the About page? Where is it? I can't find it. I see a "contributors" page, but I want to *be* a contributor, not necessarily learn about the current contributors at this time.

Where did the "help" link go?

Solutions:
1. Put a "help" link on the about page
or 
2. Rename the "Contributors" page to "Contribute"

Might be good to consider option 2. The page isn't really just about "contributors", but also about *how to contribute".

**Comment by zawmoelwin** [comment]
I can work on that @andy5995 .

**Comment by andy5995** [comment]
Hi @zawmoelwin . @julianguyen will have to let you know if this is a desired change. She'll update the ticket after some of the higher priority issues are under control, and let you know, I'm sure. Thanks again. :)

**Comment by julianguyen** [comment]
Thanks for calling this out @andy5995! Thanks for working on this @zawmoelwin, don't forget to add yourself to our Contribute page!
