### ISSUE TITLE
add "editors" to  "Contributors" page, bulletize the list

### ISSUE THREAD

**Issue by andy5995** [julianguyen/ifme#669]
> We're always looking for ideas from everyone, including mental health advocates, health professionals, software developers, translators, and user experience designers!

Correct me if I'm wrong, but wouldn't more document editors be helpful?

If added, I'd suggest a bulleted list (such as the ones tmoore are fond of) be implemented in the same PR.

**Comment by andy5995** [comment]
Also may want to consider changing the text "user experience designers". Sounds a bit technical and fancy.  Because any regular site user may have ideas regarding the experience he or she has with the site without being a professionally trained "user experience designer".

You could consider omitting it completely, and just mention it on the feedback form, or some other area where it would fit nicely. To me, it's almost implied when a site is encouraging feedback, that would be like asking "How's the general experience when you the site, Mr. or Mrs. Generic User?"

**Comment by julianguyen** [comment]
I think this is fine for now. The list of roles mentioned are not all the roles that our project are limited to. We could mention community organizers, but I think mental health advocates encapsulates that. Thanks again for bringing this up!

**Comment by andy5995** [comment]
Acknowledged! :)

From what you say, I'd assume "veterans" would fall into that category as well. It was one I hadn't suggested but thought of recently.
