### ISSUE TITLE
Add tests additional tests to medications_controller_spec

### ISSUE THREAD

**Issue by camillevilla** [julianguyen/ifme#679]
We could add some additional tests to `medications_controller_spec.rb` to increase our test coverage (see discussion in #573). Currently there are tests for:
- `#print_reminders`
- `#destroy`

`categories_controller_spec.rb` could be used as an example for additional tests (`#new`, `#create`, etc.)

**Comment by vildevev** [comment]
Hi, I am a new contributor and I would like to work on this.

**Comment by andy5995** [comment]
Hi, @vildevev . If you send an email to join.ifme@gmail.com you'll receive some details on joining our Slack workspace (chat). As for this ticket, someone will let you know its current status. :) Thanks for your interest!

**Comment by andy5995** [comment]
Oops, I see you have already done that! Nevermind. 😊
