### ISSUE TITLE
App language is not persisted after sign it.

### ISSUE THREAD

**Issue by zawmoelwin** [julianguyen/ifme#703]
Enviroment : Local Development
How to duplicate the issue : Change the site language to any language other than English.
Click sign in. Enter user name and password.
After sign in, the app language is set to English.
Click sign out. It is changed back to original language.

What it should be: After sign in, the app language should be persisted .

**Comment by tsara27** [comment]
@julianguyen I am interested to help you on this.

**Comment by tsara27** [comment]
@zawmoelwin It's working on my local development. Do you want to check it again?

**Comment by zawmoelwin** [comment]
@tsara27 You are right, it now seems gone. I just tested again and it is working fine. So, I tested on the if-me.org just to be sure and the language persisting bug is happening in "Sign in page". But I can't reproduce that bug on local environment now.

**Comment by tsara27** [comment]
@zawmoelwin Yes, the page shown in old locale. I'll help fixing that.

**Comment by julianguyen** [comment]
@tsara27 Feel free to work on this! I'll add you to the repo and you can assign this to yourself! Thanks. Thanks @zawmoelwin for calling this out too!
