### ISSUE TITLE
Move documentation into the wiki

### ISSUE THREAD

**Issue by jenniferlynparsons** [julianguyen/ifme#709]
All documentation needs to be moved into the repo wiki except for README.md, CONTRIBUTING.md, and INSTALLATION.md.

This will allow people to contribute to the docs without requiring a pull request, making it easier to keep up to date. 

The files remaining in the repo also need to be updated to redirect to the wiki pages and provide clarity on where more thorough documentation is available.

**Comment by jenniferlynparsons** [comment]
I'll be working on this over the next couple of days. :)

**Comment by timofonic** [comment]
@jenniferlynparsons @julianguyen  @andy5995 Has this been solved? Wow!
