### ISSUE TITLE
Input fields in Medications form on mobile web should take 100% width

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#713]
Currently, it looks like this:

_Hint: Use flexbox to get multiple inputs fields in Strength/Total/Dosage both take up 100%_

![image](https://user-images.githubusercontent.com/3010728/31570632-c5dd310c-b03a-11e7-9fdc-18dd8334d38d.png)

**Comment by waxidiotic** [comment]
Hey @julianguyen. I can get this done if that's cool!

**Comment by MelisaIm** [comment]
Hi! @julianguyen I could work on this :)

**Comment by waxidiotic** [comment]
@julianguyen Is this along the lines of what you were thinking or did you want the text field to take up the width and the unit field to be on the next line?

<img width="363" alt="screen shot 2017-10-14 at 12 05 10 pm" src="https://user-images.githubusercontent.com/8037469/31577184-2ed595ee-b0d8-11e7-8bdc-56dd548762ee.png">
