### ISSUE TITLE
Tests failing due to assertions following page reloads

### ISSUE THREAD

**Issue by baohouse** [julianguyen/ifme#723]
"Persisting browser locale after sign in When user sign in, sign out, then change local" in `persisting_browser_locale_after_sign_in_spec.rb` is failing. I suspect it is because the page loads asynchronously, but we don't have a wait_until the page finishes loading before we assert the page title is there.

Why it worked before might be because the page update was happening fast enough, but perhaps now it isn't. All a theory of course.

**Comment by baohouse** [comment]
Reading this resource: https://aranair.github.io/posts/2016/07/27/capybara-and-waiting/

**Comment by baohouse** [comment]
Looks like my initial analysis was wrong, sorry. Here's the test result:

> expected to find text "Profundiza en tus Momentos - eventos y situaciones que afectan tu salud mental" in "if me Página principal Momentos Estrategias Medicamento Grupos Aliados ¡Adelante! ¡Hola Some Person96! Aquí te decimos cómo empezar a compartir tus historias. Cuéntanos sobre ti. Personaliza tu Perfil - agrega una biografía y foto de perfil. Agrega Estados de Ánimo para describir mejor tus emociones. Agrega Aliados - amigos, familia, y seres queridos con los que quieras compartir. Escribe tus historias. Crea Categorías personalizadas para organizar tus momentos. Escribe sobre los Momentos - los eventos y situaciones que afectan tu salud mental. Cuídate. ¡Elabora tus Estrategias de cuidado personal! . ¿Tomas un Medicamento? ¡Realiza un seguimiento y crea recordatorios. ¿Necesitas apoyo extra? Únete a o crea un Grupo para hablar sobre ello. ¿Tienes alguna duda o pregunta? ¡Revisa nuestra página de Preguntas Frecuentes o escríbenos. if me Acerca de Blog Contribuidores Preguntas Frecuentes Socios Prensa Política de Privacidad conectarse Correo electrónico Facebook GitHub Instagram Medium Open Collective Patreon RSS Twitter recursos Comunidades Educación Líneas de Ayuda Servicios idioma English Español Português Svenska Retroalimentar Nosotros ♥ FOSS Licencia bajo AGPL-3.0"

What's really happening is that the test is unable to log back in the second time around.

**Comment by baohouse** [comment]
I learned that running this test locally is reproducible (though you may have to run it multiple times with a 30% reproducability rate). I suspect the step that clicks the sign out link doesn't complete in time before the language change step is triggered. Maybe the language is changed, a sign in occurs, and then the page finally refreshes from the sign out. That might be why we see the homepage at the time of Moments page title assertion.

I don't know why we don't just visit the signout path, but I added some expect after clicking sign out and after changing the language to make sure we're on the right page before we continue to the next step.

**Comment by baohouse** [comment]
#714 Had a failed test from the following error:

> ToggleLanguage Toggling the locale dropdown to change the language When signed out and then signed in persists locale selection from signed out to signed in state - spec.features.toggle_language_spec
spec/features/toggle_language_spec.rb
lessFailure/Error: \e[0m\e[32mexpect\e[0m(page).to have_content es_root_title
Selenium::WebDriver::Error::StaleElementReferenceError:
  stale element reference: element is not attached to the page document
    (Session info: chrome=62.0.3202.62)
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.13.0-129-generic x86_64)
./spec/features/toggle_language_spec.rb:71:in `block (5 levels) in <top (required)>'
./spec/features/toggle_language_spec.rb:70:in `block (4 levels) in <top (required)>'

It occurred after a page reload triggered by changing the language. I now have a theory that buttons/forms that trigger the page to reload is the root cause, because the test does not wait for the page to finish loading.

The solution is described here:
https://stackoverflow.com/questions/21313885/proper-way-to-wait-for-a-second-page-to-load-with-capybara-when-the-first-has-th

It's not an elegant solution, but one we have to employ. Me thinks we'll need to have a spec helper for changing languages that waits for the page to complete.

**Comment by baohouse** [comment]
Good read... https://www.varvet.com/blog/why-wait_until-was-removed-from-capybara/

So I think we'll have to get in the habit that if there is any event that we expect to reload the page (clicking submit, changing language from dropdown), we should use something like:

`page.find("#foo").should have_content("login failed")`

**Comment by sexybiggetje** [comment]
#714 also had a test blocked in  spec.features.user_creates_strategy_spec
https://circleci.com/gh/julianguyen/ifme/1708

Possibly related, since it's checked after a submit?

**Comment by baohouse** [comment]
@sexybiggetje Just merged in my fix. Hopefully it won't happen again in the future. If it does, we'll reopen this issue.
