### ISSUE TITLE
Add shortcuts to the url for language setting

### ISSUE THREAD

**Issue by sexybiggetje** [julianguyen/ifme#738]
Unless I'm mistaken, it's not possible to direct users to a localized version.
For example if-me.org/sv or /nl, /en, etc.

It's a small feature that makes sharing the site easier then saying go here, press that.

**Comment by julianguyen** [comment]
Thanks for bringing this up! This is definitely a good idea, especially for SEO purposes as well.

**Comment by jsrn** [comment]
Hi! I'd like to see if I can tackle this, if that's alright?

**Comment by sexybiggetje** [comment]
Go for it, nobody is working on it yet to my knowledge! Free drink if we happen to meet up some time.
