### ISSUE TITLE
GUI issue: Nav bar not showing 'ifme' user section

### ISSUE THREAD

**Issue by Scooterlicious** [julianguyen/ifme#74]
Using Chrome or Firefox, and the dev environment on my own machine (using a fork from today), I'm having an issue with the Nav Bar.  

When I go to 0.0.0.0:3000 (home) --> Strategies --> ifme --> The Sign out, Account, Profile do not appear.

**Comment by julianguyen** [comment]
Recent commit fixed his bug. Thanks @Scooterlicious for the catch!
