### ISSUE TITLE
Can't leave moods/categories/strategies/viewers blank when updating a Moment/Strategy

### ISSUE THREAD

**Issue by alvarocasadoc** [julianguyen/ifme#741]
I don't know if this is already reported or if I'm doing anything wrong, but I've noticed that when I try to edit a moment and remove a viewer from the list the change is not updated in the database. Below is a little demo of the bug.
![](https://user-images.githubusercontent.com/7248474/31982969-773a902e-b95b-11e7-8053-f6a48eecda91.gif)

**Comment by julianguyen** [comment]
Uhoh! Thanks for identifying this, this is definitely a bug!

**Comment by alvarocasadoc** [comment]
I'm going to try to fix this one then

**Comment by alvarocasadoc** [comment]
I've noticed this also happens to moods, categories and strategies. This bug happens only when a user is trying to delete all the viewers from a Moment or a Strategy, this means the param. array is nil when the edit form is submitted. 

My approach is to assign an empty array to the moods, categories, viewers or strategies whenever the corresponding param. array is nil due to the lack of any item selected in the list.

**Comment by julianguyen** [comment]
Thanks for offering to fix this @alvarocasadoc, much appreciated!
