### ISSUE TITLE
Working on Italian translation, need help with a sentence's meaning

### ISSUE THREAD

**Issue by Hissvard** [julianguyen/ifme#747]
Not sure whether an issue is the right place to ask about this, sorry if it isn't

I'm almost done with the Italian translation but I can't quite get what "Check in before you check out" means at line 579 of `/config/locales/en.yml`

**Comment by julianguyen** [comment]
Hey @Hissvard thanks so much for volunteering to translate to Italian :) So that line you mentioned, means something like "take care of yourself before it's too late". Hope that helps!

**Comment by Hissvard** [comment]
Thank you a lot, not even our lord and savior Google Translate could help me out this time.
