### ISSUE TITLE
Ally Invite Email Bug?

### ISSUE THREAD

**Issue by 3minus1** [julianguyen/ifme#752]
So when I try to invite an ally(tested both on production and locally), the subject of the email doesn't show up the inviter's name. And also, sender's name shows up as `smtp.sendgrid.net`

![screen shot 2017-10-28 at 11 31 46 am](https://user-images.githubusercontent.com/13695333/32131765-fcabeefe-bbd3-11e7-8c19-ff99ca179f2c.png)

**Comment by julianguyen** [comment]
Hey @3minus1, this is correct. Thanks for calling this out! @haleymnatz fixed the subject bug in a [related PR ](https://github.com/julianguyen/ifme/pull/742) . The sender name is correct, we use SendGrid :)

**Comment by andy5995** [comment]
Is that a bug I caused? (#621) The sender's name is not showing up because quotes are not used?

As for changing the "from" field from "smtp.sendgrid.net", there was a comment by @haleyelder about that in https://github.com/julianguyen/ifme/issues/127#issuecomment-327630565

>It doesn't look like if-me.org has SPF or DKIM records so, while the from address should absolutely be changed, the secret sauce will be creating a new DNS record.

**Comment by haleymnatz** [comment]
@andy5995 I don't think that's what is causing the issue, because there also aren't quotes around %{email} in the email body (as can be seen in the screenshot above - "Metal Muse"). But I could be wrong?

**Comment by haleymnatz** [comment]
I figured out the source of the issue, and have a possible solution. I assigned myself to the issue and will take it on once my other PR is pulled in (since they are both related to invitations).
