### ISSUE TITLE
strategies/new won't load when using Google Oauth

### ISSUE THREAD

**Issue by wdhorton** [julianguyen/ifme#76]
![screen shot 2015-12-05 at 1 44 04 pm](https://cloud.githubusercontent.com/assets/13503072/11609518/7e3eb780-9b56-11e5-919b-5484388e1442.png)

I get this page when I got to strategies/new when logged in with my Google account. The error on my server is this: 

ActionView::Template::Error (undefined method 'name' for nil:NilClass):
    44:       <div id="viewers" style="display: none">
    45:         <% Category.where(:userid => current_user.id).all.each do |item| %>
    46:         <%= f.check_box(:viewers, {:multiple => true, :checked => @strategy.viewers.include?(item)}, item, nil) %>
    47:         <%= User.where(:id => item).first.name  %><br>
    48:         <% end %>
    49:       </div>
    50:     </div>
  app/views/strategies/_form.html.erb:47:in 'block (2 levels) in _app_views_strategies__form_html_erb__4453707060243933365_70155494022380'
  app/views/strategies/_form.html.erb:45:in 'block in _app_views_strategies__form_html_erb__4453707060243933365_70155494022380'
  app/views/strategies/_form.html.erb:1:in '_app_views_strategies__form_html_erb__4453707060243933365_70155494022380'
  app/views/strategies/new.html.erb:1:in '_app_views_strategies_new_html_erb___3652141696081662668_70155428362280'

It appears that when using Oauth, User.where(:id => item).first just returns nil.

**Comment by julianguyen** [comment]
Looks like this bug has been fixed with this commit https://github.com/julianguyen/ifme/commit/626cf97f50b9751365b7a73c91dc0592615096dd. Thanks @wdhorton for catching it!
