### ISSUE TITLE
Notes from UX Report

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#80]
Huge thanks to the super talented Tess Gadwa for writing a usability audit on if me. To view it see: https://www.dropbox.com/s/5zftbyt3jrdfxsv/ux-report.if-me.pdf?dl=0

The following bullets are the most important points we should focus on:
- Better privacy policy, have someone with a legal background take a look at it
- Improving storytelling with Triggers feature with better writing cues, audio, and images
- Think about users who are are using the app for support primarily vs. users who are using the app to support others primarily

**Comment by markfarrell** [comment]
:+1:

**Comment by julianguyen** [comment]
@tiffanysun @hellocam

**Comment by hellocam** [comment]
Keeping this in mind for the preliminary round of user testing.
