### ISSUE TITLE
Allyship seeds cannot be created

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#82]
Allyship seeds cannot be created after running `rake db:seed` and/or `rake db:setup`

After putting debug statements in seeds.rb, the error message is coming from the different_users validation in Allyship.rb, which makes no sense because the user ids used are different and non-nil

@wdhorton

**Comment by julianguyen** [comment]
Issue was fixed, adding user_id and ally_id to attr_accessible fixed it

**Comment by wdhorton** [comment]
Glad it's fixed, but that's still weird. ActiveRecord should make all column names attr_accessible by default. I'll try to get to the bottom of it tonight or tomorrow.

**Comment by julianguyen** [comment]
Yes please review @wdhorton! :+1:
