### ISSUE TITLE
Creating new triggers/navigating through new forms

### ISSUE THREAD

**Issue by fpcyan** [julianguyen/ifme#83]
When adding a new trigger, if a category doesn't exist that fits the topic, the user cannot make one, however, they may make new strategies if one doesn't exist that fits their needs.

Navigating to the "create a strategy" page, deletes anything written in the trigger form. The user can also add new categories from this form. Again, navigating to the category form deletes any progress on the "strategies" form. Additionally, sometimes navigating forward, such as from the Triggers form to the hyperlink "Anxious" in the moods dropdown, and then navigating back, causes the form to freeze.

There are a few solutions I can think of:
simplest: open these links in a new tab, which preserves the old forms.
medium -- for moods: shows these descriptions in a modal/tool-tip.
medium -- for forms, going back and forward preserves the content. I actually thought this was a default so I wonder how to enable it.

**Comment by julianguyen** [comment]
@fpcyan So so sorry for the late response. I've been super busy the last several months!  I like the model tool tip idea for the descriptions of moods. Going back and forward should preserve the content. Let me know if you still want to work on this!

**Comment by fpcyan** [comment]
I've been busy with a new job! Hope everything is well with you here. :)

**Comment by julianguyen** [comment]
@fpcyan Congrats :) Thanks for helping out! Feel free to email me your address (join.ifme@gmail.com) so I can mail you stickers :D
