### ISSUE TITLE
Revisions to "Setting Up Postgres" in READMD.md

### ISSUE THREAD

**Issue by halfalpine** [julianguyen/ifme#94]
The command

`sudo su - postgres
`

in **"Setting Up Postgres"** is not required and caused an error, 

`su: unknown login: postgres
`

for three different users contributing to the project today on three different machines. 

We were able to avoid the error by going straight to the **"Running the App Locally"** section, and running the 

`bin/rake db:create db:migrate
`

command to continue without incident. 

Perhaps this section of the install instructions is not needed for some users? Even if it is necessary for some users, perhaps the documentation could be further clarified in this section.

**Comment by julianguyen** [comment]
Can you update the documentation to make a note of this? Thanks so much :)

**Comment by dleve123** [comment]
@julianguyen 

To add to this, I believe that specifying the user within `config/database.yml` (which is currently specified as "ifme_app") isn't necessary. Unspecified, Rails should look for a `postgres` user I _believe_.

I believe this is how [thoughtbot's suspenders bootstrapping library suggests setting up the DB](https://github.com/thoughtbot/suspenders/blob/5fcf506a8837063d4772391e5c6bd83b2090850a/templates/postgresql_database.yml.erb) as well.

If the above is correct, what do you think about removing the specification of the postgresql user?

**Comment by julianguyen** [comment]
@dleve123 @halfalpine That sounds good to me then!
